### ISSUE TITLE
DSR Support

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_public_src#119]
Does AS:RD support [DSR](https://www.nvidia.com/en-us/geforce/technologies/dsr/technology/)?

It works for me in TF2.
But the options menu in AS:RD doesn't show any resolutions higher than my native one.

**Comment by BenLubar** [comment]
I believe the resolution list is generated by the engine from this function call: https://github.com/ReactiveDrop/reactivedrop_public_src/blob/f5c844cb6a7b438b7ea82f3582f07f94ea8d484f/src/game/client/swarm/gameui/swarm/vvideo.cpp#L1300

**Comment by DukeDukeEm** [comment]
I can't do something there (I can code but I have no insight on how anything in there works).

But as an side note: 
I remember, it was working some years ago. 
I made all of my screenshots for my texture-replacement mods with DSR so I could get some good closeups on the marines models.

**Comment by BenLubar** [comment]
![image](https://user-images.githubusercontent.com/4257305/177357866-1a2b7c8e-1b0e-4c30-aa64-52dac4483194.png)

It looks like it's still working for me. I do know that NVIDIA has changed the DSR settings over time. Check NVIDIA control panel to make sure it's still enabled.

**Comment by DukeDukeEm** [comment]
It works, I forgot I need to enable Full screen instead of Windowed (borderless), sorry *facepalm*
