### ISSUE TITLE
Donations in Steam

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#128]
We have received the okay from Valve to add donation items to our game:

> **Ben:** Would adding something similar to TF2's "map stamps" make our mod commercial, or would donating to receive an icon that says you donated be okay? The idea would be to add a way to donate a dollar to a user who makes high quality workshop items, or to a category like "server hosting".
>
> **Valve:** There is a fine line between donating (which is fine) and charging for content (which is not). As long as the person donating only gets a fairly neutral marker that they have donated we are ok with it. If it gives you a desirable in-game item or effect it would be effectively paying for content.

The idea is that the donation items would be medals that cost $1, with the proceeds going to either a specific workshop creator/developer or to the Reactive Drop Team as a whole for a specific purpose (for example, there could be one for "server hosting").

The medals will be no fancier than an "I voted" sticker. Like all medals, they do not provide any in-game effect, only showing up as an icon during briefing. Unlike previous medals, you will be able to equip multiple copies of the same donation item at the same time, and this will be reflected in the item's description ("donated X times to Y").

What's left to figure out:

- Implementation
- What categories can be donated to
- How do we decide what creators can be donated to

**Comment by Blueberryy** [comment]
yeah that will make the game more alive-ish and involve more people in project

**Comment by mithrand0** [comment]
We could add a donation button to the site, and use the non-profit variant of PayPal for it:

https://www.paypal.com/us/non-profit/fundraising/fundraising-online

When doing this, we should create transparency about how much comes in, and what the funds are used for. Users should have the option to donate public or anonymous. 

Regarding payments, I am fine if we use one of the developers PayPal accounts (i.e., @BenLubar's), as long as there is a good overview of the funds coming in.

**Comment by DukeDukeEm** [comment]
Does a github sponsorship count too?

**Comment by BenLubar** [comment]
This thread is about a method of donating through Steam, which will hopefully have better visibility than existing ways of donating to RD developers.

I made a mock-up of how the donation medals could look:

![image](https://user-images.githubusercontent.com/4257305/179639271-bdd96bef-1ba2-49a0-a54b-14823db84fc3.png)
![image](https://user-images.githubusercontent.com/4257305/179639260-d2d79fd2-b5a7-4f84-9009-315633f9b115.png)

**Comment by mithrand0** [comment]
Changed the title to reflect the topic a bit better

**Comment by BenLubar** [comment]
![image](https://user-images.githubusercontent.com/4257305/187972726-41c3621a-4042-4308-9d4a-91f2dfc1aa65.png)
Currently only Nam Humanum and Accident 32 are set up with revenue splits.

- [ ] Area 9800
- [ ] Lana's Escape
- [x] Nam Humanum
- [ ] Operation Cleansweep
- [ ] Paranoia
- [ ] Research 7
- [ ] Tears for Tarnor
- [x] Accident 32
- [ ] Adanaxis

Documentation for how to set up a revenue split is here; I just need a link to the workshop item that gets created by this process to set up the item association: https://developer.reactivedrop.com/donation-items.html

Now that this is mostly set up, we can think about what other categories we want to create donation items for.

**Comment by BenLubar** [comment]
For reference, here's what you get when you click on one of those items:

![image](https://user-images.githubusercontent.com/4257305/187975235-bcf0d57d-5e67-46fe-a36b-2d5cf42e4168.png)

**Comment by BenLubar** [comment]
I've poked the Adanaxis, Area 9800, and Tears for Tarnor authors.

**Comment by BenLubar** [comment]
Paranoia is set up.

**Comment by wawawawawawawa** [comment]
> Now that this is mostly set up, we can think about what other categories we want to create donation items for.

The easiest would be to add addons in general (challenges, but also models, sounds, etc.)
Another thing would be a way to donate to rd team directly.

So far I assume it's only via github sponsorship? I personally have no clue on how that even work, and I doubt much ppl would take the time to figure out where to even click to do it (and it would mean they also know beforehand that it's the only/correct way to donate). 

Also, can you buy those tickets as many times as you want? Or is the donation capped at 1$?

**Comment by BenLubar** [comment]
You can add as many as you want to your cart and they stack. If someone knows of a way to make it so you specify how many you want to add (so if you wanted to donate $10 you wouldn't have to click 20+ times) that would be very helpful information.

I don't think there's a way to set up GitHub sponsors for an organization, but there is a way to add sponsorship information for various platforms to a repository.

Our limit for leaderboards is the 10000 limit in the Steamworks API, and we can't raise that with money. Servers would probably be set up via an existing server host, so if one person is donating for a whole server they're probably better off just going directly to the host.

**Comment by mithrand0** [comment]
> One thing to note for server though, you can't add extra priviledge like unkickable or admin priviledge or whatnot, otherwise it wouldn't be considered donation, but pay for advantage.

Admin privilege is fine, as long as only the owner has access and he doesn't abuse it.

**Comment by mithrand0** [comment]
This issue was only about map donations. I think that is finished already and this issue can be closed, correct?

**Comment by BenLubar** [comment]
The only campaigns that have been set up are the ones in the checklist above. We still need the rest.

**Comment by BenLubar** [comment]
Adanaxis looks like it was partially added - contacted the campaign author with instructions to complete the process.

Still need Area 9800, Lana's Escape, Operation Cleansweep, Research 7, and Tears for Tarnor.

**Comment by BenLubar** [comment]
Contacted Adanaxis, Tears for Tarnor, and Area 9800 authors again.

I don't have the authors of Lana's Escape, Operation Cleansweep, or Research 7 on my friends list.

**Comment by mithrand0** [comment]
> We still need the rest before we can launch.

What if the authors don't respond? Can we release without them and add them later?

**Comment by BenLubar** [comment]
> > We still need the rest before we can launch.
> 
> What if the authors don't respond? Can we release without them and add them later?

Yes, we can mark the items that aren't associated with an author as `store_hidden` in https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/community/item-schema.json

The only thing "launching" involves is making the item shop visible. Everything will still be modifiable after.

**Comment by BenLubar** [comment]
We haven't been able to find or contact the author of Operation Cleansweep. Not much information is available in the archives of Swarm Armory, so basically all we have to go by is a first name.

**Comment by jhh8** [comment]
Just to update - 

contacted Research 7 author via email (which found in res7 campaign files). Got a positive response back. After explaining the process on how to set it up, havent got a reply back in over 3 months.

Lana's author has been contacted by dmitriy via steam, also no response in about 3 months.

What about biogen corporation? Forgot what we have discussed about it

**Comment by BenLubar** [comment]
I think biogen is the same as ocs - we haven't figured out how to contact the original author.
