### ISSUE TITLE
Cannot join games of friends if they changed the language

### ISSUE THREAD

**Issue by element109** [ReactiveDrop/reactivedrop_public_src#129]

**Comment by BenLubar** [comment]
That's really weird, because I've definitely joined games with modified language settings to test things. There was Steam maintenance about an hour ago that affected lobbies. Could that have caused it?

**Comment by BenLubar** [comment]
That string is displayed if `BaseModUI::FoundGameListItem::Info::GetNonJoinableShortHint` returns an empty string, which can happen if `mpGameDetails` is null or if the number of slots is missing or 0.
