### ISSUE TITLE
Display public games on the site

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#165]
Right now, dedicated servers are listed on the site: https://reactivedrop.com/server-list.

This list shows only dedicated servers. It would be nice to show all public lobbies as well. 

The current overview is using https://steamapi.xpaw.me/#IGameServersService/GetServerList, not sure if there is a way to retrieve information for self-hosted lobbies using a web API.

**Comment by BenLubar** [comment]
I don't think you can do anything useful with lobbies through the web API. You'd need a long-running process that can run the Steamworks API with Alien Swarm: Reactive Drop's appid.

**Comment by mithrand0** [comment]
Long-running process is not an issue. I have a spare steam account that I can use. Any hints on the minimum steam API calls that need to be done for this? Or maybe a link to the RD c++ code for this?

**Comment by BenLubar** [comment]
https://partner.steamgames.com/doc/api/ISteamMatchmaking#RequestLobbyList
https://github.com/ReactiveDrop/reactivedrop_public_src/blob/reactivedrop_public/src/game/shared/swarm/rd_lobby_utils.cpp
Stuff in there that uses `SteamMatchmaking()` is relevant; stuff that uses `g_pMatchFramework` is the matchmaking.dll that Valve provided, which is tightly coupled with the engine, so not useful here.

**Comment by BenLubar** [comment]
If you try to do anything you're not allowed to (like reading the member list of a lobby you're not in) you'll generally get a zero-value response.
