### ISSUE TITLE
Controller move and aim

### ISSUE THREAD

**Issue by Nyubs** [ReactiveDrop/reactivedrop_public_src#17]
is it possible to make the leftstick only move a marine and the right stick only aim?
right now if you are not holding the right stick while moving the view changes into the run direction.

can this be changed? or maybe already a console command exist?
maybe add it to controlls for controller.  atleast i couldnt find one option to change that behavior.

most twinstick shooter work like that, moving and aiming seperated.

much luv Nyu

**Comment by BenLubar** [comment]
Closest thing that currently exists is `joy_aim_to_movement_time` which defaults to 1 second, so you could set that to something much higher to prevent the left stick from turning the marine.

There's also `joy_lock_firing_angle` which does what you want, but only while shooting.

**Comment by AutoGavy** [comment]
> Closest thing that currently exists is `joy_aim_to_movement_time` which defaults to 1 second, so you could set that to something much higher to prevent the left stick from turning the marine.
> 
> There's also `joy_lock_firing_angle` which does what you want, but only while shooting.

Thanks, great help for me

**Comment by AutoGavy** [comment]
> > Closest thing that currently exists is `joy_aim_to_movement_time` which defaults to 1 second, so you could set that to something much higher to prevent the left stick from turning the marine.
> > There's also `joy_lock_firing_angle` which does what you want, but only while shooting.
> 
> Thanks, great help for me

Thank nyu to write issue too

**Comment by AutoGavy** [comment]
> Closest thing that currently exists is `joy_aim_to_movement_time` which defaults to 1 second, so you could set that to something much higher to prevent the left stick from turning the marine.
> 
> There's also `joy_lock_firing_angle` which does what you want, but only while shooting.

one more issue, seems controller cannot control remote truret's facing that operates in a terminal
