### ISSUE TITLE
friendly fire graph

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#170]
1000 year old bug: dealing friendly fire to yourself shows the damage done at the beginning of the timeline instead of when it was actually done. might be also more cases when this bugs out, dont remember exactly

**Comment by BenLubar** [comment]
That's really weird, because `CASW_Marine_Resource::m_TimelineFriendlyFire`, like all other `CTimeline` instances, is append-only, and there's only one place where it's written to, and it's the same logic no matter which marine did the marine damage.

**Comment by wawawawawawawa** [comment]
In case of, I have a record of this happening to me, yet it wasn't even self friendly fire.
The tk happens near 1:25 (4k dmg since wb hand nade damage), yet it shows at start.
https://www.youtube.com/watch?v=rOzMNWF45-U

**Comment by BenLubar** [comment]
Hmm, I wonder if it's not showing 0:00 but rather the first time friendly fire damage was dealt on the left of that chart.

**Comment by BenLubar** [comment]
found it by manually computing what the code would have done!
