### ISSUE TITLE
bonus missions character unpicking

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#171]
after restarting a bonus mission the marines always get unselected, probably because the game does not build a campaign save

**Comment by BenLubar** [comment]
Was this on the live branch or the beta branch? Can't reproduce on beta.

**Comment by jhh8** [comment]
was on live

**Comment by BenLubar** [comment]
Already fixed. 👍

**Comment by jhh8** [comment]
figured out the problem but dont know what to do. 

when we launch a mission from main menu, the engine->GetLaunchOptions() outputs these keyvalues: "map", "rd-bonus_mission1", "single-mission"
when we launch a mission from the f9 menu when we are inside a mission already, the launch options look like this: "changelevel", "rd-bonus_mission1".

in this case we dont have the "single-mission" keyvalue, which means in the game resource constructor the m_szCampaignSaveName member is set to null. which means ASWGameResource()->GetCampaignSaveName()[0] is false and CreateCampaignSave() doesnt get called in asw_gamerules.cpp line 8903

**Comment by BenLubar** [comment]
Thanks, found the bug.
