### ISSUE TITLE
[bug] main volume control bar is placed at wrong place

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#177]
![snapshot0001](https://user-images.githubusercontent.com/11514506/182121617-cb4fcd55-5047-4c33-a8b7-a264196b673d.jpg)

**Comment by BenLubar** [comment]
The `volume` (overall game volume) convar goes from 0 to 1, with 1 being the default. Other volume-related convars use the new mixer system which doesn't have a hard limit, so they go from 0 to 1.5, with 1 being the default. Or am I misinterpreting what you mean by "placed at wrong place"?

**Comment by ywgATustcbbs** [comment]
> The `volume` (overall game volume) convar goes from 0 to 1, with 1 being the default. Other volume-related convars use the new mixer system which doesn't have a hard limit, so they go from 0 to 1.5, with 1 being the default. Or am I misinterpreting what you mean by "placed at wrong place"?

![IMG_20220802_020223](https://user-images.githubusercontent.com/11514506/182212846-5f4dd082-e49d-4031-bb56-fde11c624267.jpg)

**Comment by BenLubar** [comment]
The vertical lines show the default setting for each slider.

**Comment by ywgATustcbbs** [comment]
> The vertical lines show the default setting for each slider.

Sorry I made a mistake.
