### ISSUE TITLE
[bug] accident 32 map 6 shows 4 collect data objectives

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#182]
![-3a48ffe18307d11b](https://user-images.githubusercontent.com/11514506/182683647-f639c521-e093-4a2e-8da0-ec613cf172e8.png)

Map would pick 3 out of 4 (i guess). Most of the time it worked fine. But sometimes 4 target areas were shown. Only 3 had data.

To be more precise, my friend(host) saw 4 targets, while i(client) only saw 3. This happed several times while playing.

**Comment by jhh8** [comment]
Knew about this issue, no idea whats going wrong.  Probably instant restart breaking simething
