### ISSUE TITLE
Proposal: Remove mentions of centuries from Alien Swarm canon

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#184]
(Vote with 👍 or 👎 on this issue. Feel free to also leave a comment if you want.)

The idea is to remove centuries from years, so that the story happens ~~within a single century, but it could be~~ in any century. Jacob's Rest could have happened in 2052, 2252, or 20052.

**Comment by DukeDukeEm** [comment]
@jhh8 wasn't it your map containing the centuries? And now you vote for removal? 🤪

**Comment by jhh8** [comment]
I vote to remove the 2232 you set and leave 32 so most people can interpret it normally as 2032

**Comment by ThisIsABug** [comment]
You mean the once which are too young to interpret what 20 years in human history could mean?

**Comment by DukeDukeEm** [comment]
Well you started the idea of giving the story a century, if you want do burry it, sure, step forward and change it, it‘s your original contribution.

**Comment by jhh8** [comment]
original paranoia had the year 2060 in mail, operation cleansweep has year either 2005+ or 2065+ in the overview of map3. Many other maps mention syntek in their story so they kept the same date format as in jacobs rest. im not a fan of throwing all campaigns into the same universe as jacobs rest just because it was the main campaign in the original game. many campaigns did choose to do so by mentioning the things mentioned in jacobs rest

**Comment by jhh8** [comment]
in my eyes this change wouldnt move all campaigns into one century, it would leave the century open for interpretetion by other people. accident 32 does not have any highly futuristic elements and the century would be interpreted to be the 21st one. adanaxis has a lot of highly futuristic elements and the century would be interpreted as 22nd or 23rd

**Comment by DukeDukeEm** [comment]
> original paranoia had the year 2060 in mail

Can you point me please to this mail?

> operation cleansweep has year either 2005+ or 2065+ in the overview of map3

I think what you are referring to is just for cool background fx, the text which you are seeing is the starting point of an old textadventure named ZORK:
![image](https://user-images.githubusercontent.com/69652463/185718501-faf075c5-17b2-4dc3-a40f-ba0ce93b9bfa.png)

**Comment by jhh8** [comment]
mail from the original paranoia campaign, found either in moddb or rd workshop
![image](https://user-images.githubusercontent.com/95616101/185718814-128e65fc-4072-4dd0-8b63-9078d833cae6.png)

in ocs the top left corner of the overview of map3 is zork yes, but im referring to bottom right and bottom left corners which look like mails
![image](https://user-images.githubusercontent.com/95616101/185718996-3f05ac2d-e85f-411b-8dbb-22534383ef13.png)

**Comment by DukeDukeEm** [comment]
> im not a fan of throwing all campaigns into the same universe

it's the same universe, as you said, same companies and so on

> accident 32 does not have any highly futuristic elements and the century would be interpreted to be the 21st one. adanaxis has a lot of highly futuristic elements and the century would be interpreted as 22nd or 23rd

one exception in a theme does not automatically make the rest of the theme irrelevant, it can be interpreted as a dream sequence for an example, that's more likely then using the same guns for 300 years

**Comment by DukeDukeEm** [comment]
> mail from the original paranoia campaign, found either in moddb or rd workshop

modding-scene ... great ... can (and should) be everything possible, without any needed constrains in canon

> in ocs the top left corner of the overview of map3 is zork yes, but im referring to bottom right and bottom left corners which look like mails

there's a textadventure in between, take it easy

**Comment by DukeDukeEm** [comment]
@Nyu please calm down, it's not twitter

**Comment by BenLubar** [comment]
Unless explicitly stated, the campaigns are not canon to each other. The squad of marines that went through Jacob's Rest is not the same as the squad that went through Tears for Tarnor (and they may not have even existed in the same universe).

**Comment by jhh8** [comment]
so now that you know why i am voting for this change, tell me why are you voting against it? what does it change about your interpretation?

**Comment by DukeDukeEm** [comment]
> Unless explicitly stated, the campaigns are not canon to each other. 

True, but at some point you can decide for some consistency in a group of things, that's not giving up on the freedom of including everything you want later on. Your statement makes perfectly sense, and I'm not the butcher which tries to force that through. But there is hardly a reason not to do it if it doesn't harm anyone.

> The squad of marines that went through Jacob's Rest is not the same as the squad that went through Tears for Tarnor (and they may not have even existed in the same universe).

Same names, portraits, colors, voices, voicelines ... c'mon.

**Comment by DukeDukeEm** [comment]
> so now that you know why i am voting for this change, tell me why are you voting against it? what does it change about your interpretation?

consistency, in a package of things, somebody gets

**Comment by jhh8** [comment]
if im not mistaken we only found out the exact century not long ago in this thread https://steamcommunity.com/app/563560/discussions/0/3421062958699939882/

so as mysterious, irrelevant and hard to find the actual century it was before, will be the same after the change. so from your point of view  not much will be different after this change

**Comment by DukeDukeEm** [comment]
Ben found a reference to 2252 and you found a reference to 2060, both are in the base-game files, and as far as I know they both aren't loaded.

Look, we have the chance to straiten some content up here and we can take it so it looks better to the people which see this nice piece of software at a point later in time. But if it destroys your vision please change what you want to change. I do not have the final word here, I'm trying to bring sense into that stuff, that's nothing destructive and for sure nothing against your point of view in it.

**Comment by DukeDukeEm** [comment]
@jhh8 FYI: about the pictures at the bottom of the map: the left one is cutoff content from the right picture, and where is it from?
An Google patent for a paymentsystem from February of 2006

![image](https://user-images.githubusercontent.com/69652463/185754968-f4bca488-f58f-4157-8e87-d8ac810d1d0f.png)

Source:
https://www.seobythesea.com/2007/09/google-checkout-precursor-gbuy-more-ambitious-than-paypal/

**Comment by wawawawawawawa** [comment]
I know this just got closed, but wanted to say, there is a reference to 2232 from the [wiki ](https://alienswarm.fandom.com/wiki/Oasis_colony): 
`"On the 2nd of February 2231 (about 21 years prior to the events of [Jacob's Rest](https://alienswarm.fandom.com/wiki/Jacob%27s_Rest)), Oasis colony was founded, when the 1st construction ships made planetfall. Ever since then, the 2nd of February has been a national holiday on Tarnor to celebrate this. The original colony was limited in equipment, as funds were not inexhaustible. As such, the communication systems had to be built away from the colony proper, on higher ground, where the systems could better cut through the strong natural magnetic field that protected Tarnor from the brunt of it's star's intense radiation."`
