### ISSUE TITLE
New tabs - background

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_public_src#185]
I wouldn't count this as a bug, but just to tell you it's like that, the new tabs have a blurry background in which the used string is duplicated. One of my translations (the first tab 'campaigns') is multi-line (I'll remove that) and shows the following effect.

![image](https://user-images.githubusercontent.com/69652463/183247564-127baf01-f8c0-49b9-bba5-392e34b47b57.png)

My translation string is "Feldzüge\n(mehrere Einsätze)". It describes the difference between a campaign and a mission, in saying "Campaigns (multiple missions)". I just replaced it with "Feldzüge (mehrere Einsätze)" to keep the differentiation and go along with the nicer one-line title.

**Comment by BenLubar** [comment]
I can tell you what's causing this - the white text gets auto-resized as part of the tab sizing algorithm, which sets both its width and height. The black shadow does not have its height changed, and the text is centered on both labels, so the vertical positions of the text becomes different.

The rest of the tab's panel hierarchy doesn't change height, so the white text gets clipped by the tab panel.
