### ISSUE TITLE
Add hack hint for new players

### ISSUE THREAD

**Issue by Dumbstep** [ReactiveDrop/reactivedrop_public_src#19]
Add env_instructor_hint to the computer hack of the landing bay, most new players do not know how to complete.

**Comment by BenLubar** [comment]
I think we could achieve the same goal by making the "subsystem process alignment" text more prominent

![Alien Swarm tumbler hack](https://user-images.githubusercontent.com/4257305/170916083-c8671929-e3df-45f7-990c-aeff59158415.png)

**Comment by Dumbstep** [comment]
OK, localized text needs to be added

**Comment by BenLubar** [comment]
It should be under `asw_hacking_tumbler_alignment`
