### ISSUE TITLE
Accident 32

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#190]
Campaign polish checklist:
- [x] Soundscapes
- [x] Overviews (minimap, briefing)
- [x] Mission chooser text
- [x] Campaign transition screen (map, coordinates)
- [x] All UI strings translatable
- [x] Speedrun times

Add files:
- [x] Assets (in staging repo)
- [x] Maps (in public_src repo)
- [x] Text (in translations repo)

Admin work:
- [x] Add as official in C++
- [x] Add compile params to `build_maps.py`
- [x] Stats/Achievements added to Steam (near release)

**Comment by jhh8** [comment]
are soundscapes really needed tho?

**Comment by BenLubar** [comment]
Since each map is a single pretty consistent theme, you could probably get away with just one env_soundscape per map.
