### ISSUE TITLE
[bug] accident 32 and achievement bugs

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#194]
Accident 32 map 3, bot would teleport outside the bridge surface and then get killed (near the 3rd data). 

Map 4, the door near the starting area will get stuck with no reason. Mobs behind can't get out. It's not frequently observed. 

Previously obtained speedrun achievements (accident 32 speedruns) are locked again. Not sure if this is a bug.

Beta, console font size (and chat perhaps) is too small. Is it intentional? A small font size is hard to read for one with bad eyesight like me.

**Comment by BenLubar** [comment]
Does the text size look better after the hotfix?

**Comment by ywgATustcbbs** [comment]
> Does the text size look better after the hotfix?

console text is ok now
