### ISSUE TITLE
instant restart camera position

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#198]
after isntant restart the camera is still located for a brief moment in the place where mission failed, could that be affecting sleeping aliens or prespawns on onslaught because of pvs being rendered there for a brief time?

**Comment by BenLubar** [comment]
I think this is because the player entity doesn't get moved back to its original spawn position. I'll fix.

**Comment by BenLubar** [comment]
Looks like it only affects the client, so this isn't what's causing the spawning problems.
