### ISSUE TITLE
Player information in matchmaking tags

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#201]
Is it possible to add the player names or steamids of the players in a lobby to the matchmaking tags, like it was done with:

```
  "system:rd_lobby_location": "hkg=128+12/129+12,sgp=162+16/158+12,seo=267+26/165+12,tyo1=236+23/179+12,tyo=253+25/180+12,maa=327+32/191+12,bom=436+43/207+12,fra=232+23,dxb=341+34/233+12,ams=310+31/237+23,iad=365+36/318+23,gru=509+50/453+25"
```

In example:

```
"system:rd_players": "BenLubar,jhheight,Mithrand"
or
"system:rd_players": "57999145,53299860,217437827"
```

With this, the website could show the player names in a lobby, like it does for dedicated servers.

![image](https://user-images.githubusercontent.com/28685162/184676037-d8d8a7bc-01e5-4f19-95f8-5c675c860bf0.png)

**Comment by BenLubar** [comment]
I don't know if we want to do this for privacy reasons, but it definitely *can* be done.

**Comment by mithrand0** [comment]
@BenLubar Maybe we can do it the same way as dedicated srcds servers. Those already giving the player names, but not steamid. For the server browser on the site, this would be more than enough.

**Comment by ywgATustcbbs** [comment]
> I don't know if we want to do this for privacy reasons, but it definitely _can_ be done.

Anyway, player names and ids are public as a user can join the lobby and see their names and steam ids. Those are searchable when adding steam friends.

**Comment by mithrand0** [comment]
The `system:rd_lobby_location` tag contains the steam site, ping and jitter to that site. With that information, you can get the closest location, and it's country the user is connected to.

**Comment by BenLubar** [comment]
That string is from https://partner.steamgames.com/doc/api/ISteamNetworkingUtils#ConvertPingLocationToString - we're not technically supposed to be parsing it ourselves, but SteamDB is tracking the global Steam Datagram Relay config here: https://github.com/SteamDatabase/SteamTracking/blob/master/Random/NetworkDatagramConfig.json

**Comment by BenLubar** [comment]
You need to call https://partner.steamgames.com/doc/api/ISteamNetworkingUtils#InitRelayNetworkAccess once in order to know your own ping location.
