### ISSUE TITLE
crash after opening a lobby the second time

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_public_src#204]
Since some time now the game crashes after opening a lobby the second time.
STR:
* Open normal lobby
* Start game
* Go back to main menu
* Open a new lobby

**Comment by mithrand0** [comment]
Is it every lobby combination with every map, or only specific ones? Can you in example connect to two dedicated servers without crashing?

**Comment by DukeDukeEm** [comment]
I create my own server, click on the first campaign and then the first mission, leave the standard settings and create the lobby.
