### ISSUE TITLE
Korean Characters are not displayed.

### ISSUE THREAD

**Issue by 906bc906** [ReactiveDrop/reactivedrop_public_src#212]
![image](https://user-images.githubusercontent.com/57206558/186060269-110db2a1-d4fc-4fa6-90a8-9c064aac93ef.png)

![image](https://user-images.githubusercontent.com/57206558/186060384-32d07384-21d2-43a2-aaa6-2a8252a9bb33.png)

After Aug 22 update, Korean characters are not displayed. 

> The game now uses Noto Sans SC as its default fallback font instead of an arbitrary system font.

I think this change caused the problem. Noto Sans SC has only Simplified Chinese characters and part of Japanese characters, so can't handle Korean characters.

I'm sorry I tried solve this problem but failed.

## Try 1

replaced `Noto Sans SC Regular` with `Noto Sans CJK SC`.

rd_font_hack.cpp
```c++
#define REPLACEMENT_FONT_PATH "resource/NotoSansCJKsc-VF.otf"
#define REPLACEMENT_FONT_NAME "Noto Sans CJK SC"
```

You can download Noto Sans CJK SC from here : https://github.com/googlefonts/noto-cjk/releases/tag/Sans2.004

(All Variable OTF/OTC -> Variable -> OTF -> NotoSansCJKsc-VF.otf)

Docs for Noto Sans CJK SC : https://notofonts.github.io/noto-docs/specimen/NotoSansCJKsc/

![image](https://user-images.githubusercontent.com/57206558/186096004-0f464e85-548f-4e30-9bbd-0b2e12f1ee87.png)

![image](https://user-images.githubusercontent.com/57206558/186097195-4e5fc1a8-f1fc-425e-8a2b-1044bb5f10a8.png)

![image](https://user-images.githubusercontent.com/57206558/186096097-6b5e79c8-1a11-42c6-a633-dda30582dbf6.png)

Some characters are not displayed.

## Try 2

Replaced `Noto Sans SC Regular` with `Noto Sans Mono CJK SC`.

rd_font_hack.cpp
```c++
#define REPLACEMENT_FONT_PATH "resource/NotoSansMonoCJKsc-VF.otf"
#define REPLACEMENT_FONT_NAME "Noto Sans Mono CJK SC"
```

(All Variable OTF/OTC -> Variable -> OTF -> Mono -> NotoSansMonoCJKsc-VF.otf)

![image](https://user-images.githubusercontent.com/57206558/186101209-1d6c05ec-e0b7-4abe-8075-9b135304c5a2.png)

![image](https://user-images.githubusercontent.com/57206558/186101221-3c488ed5-cbcb-47a6-ab77-90af07978c85.png)

![image](https://user-images.githubusercontent.com/57206558/186101443-a91a670e-6b56-4b19-845e-4e8996bcefcc.png)

most of them are displayed well, but korean characters on dedicated server list and console are displayed partially.

![image](https://user-images.githubusercontent.com/57206558/186106690-eddf66b8-0f71-4eda-a39f-b99cffe2676a.png)

above all, Chinese characters are not displayed properly.

## others

Korean characters(hangul syllables) range from U+AC00 to U+D7AF[^wiki-hangul], and widths of korean letter for noto mono sans cjk sc are 1.426.[^letterwidth]

[^wiki-hangul]: https://en.wikipedia.org/wiki/Hangul_Syllables

[^letterwidth]: ![image](https://user-images.githubusercontent.com/57206558/186102929-05d6d2ee-a75d-4251-8fd2-159a16836c00.png) (가, a, 뷁, ㄹ)

![image](https://user-images.githubusercontent.com/57206558/186101749-732cbf62-dd4f-4bd9-b05e-9ed885f7996e.png)

I set language to Simplified Chinese in game property, but dedicated server list are written in Korean.

![image](https://user-images.githubusercontent.com/57206558/186109930-196485f3-1317-4273-b2b5-be29a67faf6a.png)

Then, I set language to English in *Steam* settings, and dedicated server list are written in English. 

## conclusion

I think need to use different fonts for different languages, or use arbitrary system font for Koreana.

**Comment by BenLubar** [comment]
I've reverted the font change entirely.
