### ISSUE TITLE
crucial point ending is cheesable

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#216]
https://steamcommunity.com/app/563560/discussions/2/3464976518715210949/

**Comment by jhh8** [comment]
suggestion: why not make illyn forest (and now crucial point) have only techs hack the panels to reenable them back to working? with recent tech requirement changes, if we have a tech requirement disabled and enable it when techs are not alive, it will automatically fail the mission

**Comment by jhh8** [comment]
oh my god this bug was in the game the whole time
![image](https://user-images.githubusercontent.com/95616101/186191416-249b4664-7942-4561-b6f5-f5342b831e1a.png)

**Comment by jhh8** [comment]
when compiling the map
![image](https://user-images.githubusercontent.com/95616101/186196843-5fda124e-5c62-4aa6-9a8b-b8cfd4131683.png)

this is a keyvalue in npc_bullseye entity

**Comment by BenLubar** [comment]
will rename
