### ISSUE TITLE
[bug] accident32 map 6 missing door map

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#223]
the door is missing its map

![acc32-6研究所废墟-粗剪 mp4_20220826_030335 200](https://user-images.githubusercontent.com/11514506/186752711-6ad4623a-4a7d-4b33-be04-5cfa700e8a4c.jpg)
![acc32-6研究所废墟-粗剪 mp4_20220826_030224 909](https://user-images.githubusercontent.com/11514506/186752727-db5e0bc0-0387-4b6e-a48b-d727f4e4dde5.jpg)

**Comment by jhh8** [comment]
what does this mean?

**Comment by ywgATustcbbs** [comment]
> what does this mean?

The slow opened door is black while it should have a texture map

**Comment by jhh8** [comment]
dont know what to tell you, thats just a dark door
