### ISSUE TITLE
implement text filtering

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#24]
We can now use the [text filtering API](https://partner.steamgames.com/doc/api/ISteamUtils#FilterText)

- [x] Filters text according to the settings on [the user's Store preferences page](https://store.steampowered.com/account/preferences#CommunityContentPreferences).
- [x] Can be disabled entirely with `rd_text_filtering 0` (if you want to filter text for other games but not this one for whatever reason)
- [x] Filters display names on leaderboards
- [x] Filters display names on HUD
- [x] Filters chat

Only runs on client. Does not filter game content (there's simply too much of it, and determining whether something is official or from an addon as well as who made the addon at runtime would be a lot of extra computations and API calls)

**Comment by mithrand0** [comment]
Oh nice, we just saved me some work 👍
