### ISSUE TITLE
Portable amplifier temporarily breaks Infinity challenge

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#242]
Back when the backpack cvar started with "rda_", [Infinity](https://steamcommunity.com/sharedfiles/filedetails/?id=1998911297)'s instakill of enemies somehow did not work with backpacks on. That's no longer the case, but now there's another back-appender: the sticky version of the amp cancels challenge's ammo/item superregen (and sometimes instakill, again) until amp's duration runs out. Is this a game problem or this specific challenge's problem?

**Comment by BenLubar** [comment]
ok, looks like the challenge is doing a loop over all objects attached to the marine and assuming that they all understand ammo as a concept. It's a bug with the challenge, but it should be fairly easy to fix - just check that the object has a GetMaxClip1 method before calling it and if it doesn't, skip it.

**Comment by WhenTanksFly** [comment]
This abandonware was never to be fixed by the author, probably should've closed the issue right away. Maybe someone els-
ugh, challenge stopped being accessible some time ago, so I guess I might as well close for irrelevancy.
_Good to have a backup, though All In One is generally more useful for testing anyway._
