### ISSUE TITLE
Deathmatch: in demos non-loaded profile pictures get overridden by others'

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#244]
Apparently anyone whose profile pic hasn't been loaded yet in current Steam session (effectively anyone not in friends list) will have their pic displayed as plain white rectangle in DM demos. Not sure if that's how it's supposed to be, but okay.
Yet me seeing multiple myselves after swapping places with someone with blank pic shouldn't be happening. I wonder if my pic isn't being cleared from the old position because there isn't quite another pic to replace it with.
How the top panel looked during the game after I scored the first kill & already overscored someone still at 0 kills VS how it looks in demo at the same timestamp after Steam restart, with the [leftmost player](https://steamcommunity.com/profiles/76561198447620916/) being friended:
![crabs_are_taking_over](https://user-images.githubusercontent.com/112336094/187499558-31ae9281-eed5-40d9-9879-22c996e6ce44.png)
[dm_demo.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/9452328/dm_demo.zip) (v7.1.3.5)

Unrelated, but this small demo is 6.5 Mb. Is this how big demo files are supposed to be, or did I screw something up with mods or settings? Vaguely remember them being smaller years ago, it might've been the [cursor recording changes](https://steamcommunity.com/games/AlienSwarmReactiveDrop/announcements/detail/1674703076071264669)...

~~Also, cool midair double gun grab at tick 4300+~~

**Comment by ywgATustcbbs** [comment]
Btw, the demo size of wrf-8 is about 3x the size of mine. While others are almost the same size of mine. We tried to speedrun in beta with 3 friends, We all recorded our demos. 

After demos collected, wtf8 got a ~150mb demo while mine and other friends are only ~50mb. I can provide all demos For analysis if necessary
