### ISSUE TITLE
Nam Humanum - Platform XVII: Bot pathing bad

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#253]
Even after fixes it still often leads them backwards or/and away from the team, especially in the second building with all that extinguishable fire; asw_follow_use_hints 0 performs much better. Is it possible to at least shut the custom hints down on the way back?

**Comment by BenLubar** [comment]
We now have movable marine hints, which should greatly help with moving onto or crossing the titular platform.
