### ISSUE TITLE
Bring back Cleansweep's and Tarnor's old icons?

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#266]
Can't find associated changes mentioned in the News section on Steam, but long ago these 2 campaigns had icons different from their "next mission" screen. With the new mission selector that shows both that screen's image and the normal icon, it looks like they're missing their normal icons and use press-continue-button-again screen's as placeholder. How was that orange-green mess deemed cooler than a red planet with a half-eclipsed star and background stars?
If the icons were lost by now, they could be taken from legacy campaign versions on Workshop, hopefully they aren't in lower resolution or something.

**Comment by BenLubar** [comment]
These icons?

![image](https://user-images.githubusercontent.com/4257305/188175804-20d2d7db-7005-4d54-86c8-cb35de721261.png)

Where are they missing from?

**Comment by WhenTanksFly** [comment]
asudfygdhkjhsrf Ok this was not a game problem, the [Autogun Ammo GPS+](https://steamcommunity.com/sharedfiles/filedetails/?id=1811259113) mod did it. Wonder how much more junk is hidden in those 500 Mb.
