### ISSUE TITLE
Crash memory dumps

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#272]
Several memory dumps. Today i encountered two or three game crashes. Possibly due to too many fast restart when speedrunning.

https://1drv.ms/u/s!AjHhxntCwFpDttwtGcsYgCKObyZeJA

**Comment by BenLubar** [comment]
Hmm, most of these are engine, some are an old version of the mission parser, some are that particle crash I still can't figure out.

**Comment by mithrand0** [comment]
I think we can safely close this because of the age.
