### ISSUE TITLE
Ricochet rifle's laser trajectory predictor is invisible in some campaigns

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#279]
I see it in Nam Humanum, BioGen, Research 7 and Lana's Escape, but not in Jacob's Rest, Cleansweep, Tarnor, Paranoia, Area 9800 or Tilarus. Tested entire Nam Humanum, BioGen and Cleansweep, and one mission of every other. While normally unincluded weapons are expected to be incomplete, this is some weird inconsistency.

**Comment by BenLubar** [comment]
This was fixed when I completely rewrote the laser pointer for the ricochet rifle, but I forgot to close the issue.
