### ISSUE TITLE
User lobby player information broken

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#286]
The user lobbies do not provide player information any more:
https://steamuserimages-a.akamaihd.net/ugc/1790765893240838526/DE11B793E82EA1002AA2955C49FFE1934AB35AFE/

This might (or might not) be related to something that has changed in:
https://steamuserimages-a.akamaihd.net/ugc/1817787491004282381/A2B7947C5BB3988E8BEB2D08668844B8F774F861/

**Comment by BenLubar** [comment]
https://partner.steamgames.com/doc/api/ISteamMatchmaking#SetLobbyData says the strings can be up to 8192 bytes, so we shouldn't be anywhere near the limit

a server with 32 players that each have max-length unicode steam names would hit the limit but our format string would truncate it, so it would still show up in the lobby details :/

**Comment by mithrand0** [comment]
This has been fixed a while ago.
