### ISSUE TITLE
question about changes in the steamapi

### ISSUE THREAD

**Issue by Nyubs** [ReactiveDrop/reactivedrop_public_src#29]
https://steamcommunity.com/sharedfiles/filedetails/?id=2814826145

was the steamapi updated? Updated Steam API from 1.38a to 1.53a?

is it possible to make a experimental version that doesnt use the new one?
systems that cannot use the newest steamclient cannot play the game

just to remind you of the store page:
MINIMUM:
OS: Windows® XP or above
newest steamclients dont work on vista or xp

with old api it still playable with a old steamclient.

greeting Nyu

**Comment by BenLubar** [comment]
[CS:GO](https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/) claims to support Windows XP on its store page and as far as I can tell is running on either Steamworks API 1.51 or 1.52.

Do you know anyone who's using Windows XP or Vista? I'd like to get into contact with them to set up a testing environment.

**Comment by mithrand0** [comment]
https://help.steampowered.com/en/faqs/view/6E66-54EC-3EFC-283C

```
Steam Support - Windows XP and Windows Vista Support

As of January 1 2019, Steam officially stopped supporting the Windows XP and Windows Vista operating systems. The Steam Client will no longer run on those versions of Windows. In order to continue running Steam and any games or other products purchased through Steam, users will need to update to a more recent version of Windows.

The newest features in Steam rely on an embedded version of Google Chrome, which no longer functions on older versions of Windows. In addition, future versions of Steam will require Windows feature and security updates only present in Windows 7 and above.
```

**Comment by Nyubs** [comment]
mithrand like always doesnt read and posting copypasta.

so ben, thanks for answering, i know its not normal to have someone still use it.
but a friend of mine played for years on vista asrd, his pc is too bad to handle newer OS. i think you should see the persons name in the link.
just the change to the api made the game not playable anymore with the old steamclient.
alot of games still work. the once that dont work, give either a error, or they bug out aka give messages like in screenshot on trying to play.

sorry for not checking the issues, i got lost in factorio after i posted this.

would it be possible to use old API in a beta like branch? (not even sure if he could use these) and still play with others who use the normal api?

and if not possible, maybe just update the storepage, you know how valve cares of updating their own games.

**Comment by mithrand0** [comment]
Valve revoked the support, because of security reasons. Running Windows XP, Vista these days is not secure when doing things on the internet. Windows Vista was a resource hogger, your friend should be able to run Windows 7 fine (which is also end of life, but should be able to run the latest Steam).

Regarding the Steam API update, I don't have an opinion on that and leave this up to @BenLubar.

**Comment by Nyubs** [comment]
censoring my point that he copypastas and doesnt read at all and he does it again litterally writing the same copypasta.


you also dont know anything about pcs if you think everyone can run windows 7 or 10 on old machines, not everyone has parents to throw money at you.

and funny how whole communities still exist that use old windows, alone windows xp has thousand of people who run it.
if you read once behind your copypasta you would know that.
just communities like for example i wanne be the guy fangames run old OS's cause of input delay or compability reason to play perfectly.
but sure copy the copypasta. and forget the real point they stopped supporting cause it costs money, and its old.

so ben dont listen to this guy pls.  i dont care how you decide ben, but i know you atleast have a brain.
we both knew what he wrote 5 years ago, its just copypasta to look like he does something.
real input comes from you only in this thread, ben :3
much luv for the real devs

**Comment by BenLubar** [comment]
The new version of the Steam API is used for things like lobby ping estimates, medals, and text filtering. It is not feasible at this time to maintain two "live" versions of the game with different levels of feature support and bugfixes.
