### ISSUE TITLE
Nam Humanum - Groundwork Labs: Indecisive AI pathing near collapsible stairs after huge door

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#304]
I think I've just witnessed 2 drones debating which way should they go.
[there_no_there_tick4800_v7136.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/9620949/there_no_there_tick4800_v7136.zip)

**Comment by geotavros** [comment]
Should be fixed by 7f8f5c3591434b60560e0a48e2e29bdb8e758477
