### ISSUE TITLE
[suggestion] send dump file at game startup

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#319]
Many users might have encountered game crashes. And they just restarted the game and play. Even unaware of there was a dump file created. Many users never open the game folder.

If the game adds some kind of ingame feedback, more bug reports are expected. And devs can get more bug info from various dumps.

My idea is, to monitor if there is any created dump file at game startup. Then ask the user if he wants to send the file. If yes, send the file (maybe via the existing website post method). Whatever the user choice is, delete the dump file.

**Comment by mithrand0** [comment]
It would be preferred to use an existing tool for this. Crashpad & Sentry could come into play:
https://docs.sentry.io/platforms/native/guides/crashpad/

**Comment by ywgATustcbbs** [comment]
> It would be preferred to use an existing tool for this. Crashpad & Sentry could come into play: https://docs.sentry.io/platforms/native/guides/crashpad/

Do players need to download and install it, or the game will integrate it into the source code in the future? If players need to do something other than click in the game, i think few people will try to use that

**Comment by mithrand0** [comment]
Players don't need to download anything

**Comment by BenLubar** [comment]
Steam automatically uploads crashes for 32-bit Windows games already

![image](https://user-images.githubusercontent.com/4257305/193080837-a505f125-7e7e-4353-af33-d20ad2c508ec.png)

**Comment by mithrand0** [comment]
Seems minidumps are already sent, closing the issue.
