### ISSUE TITLE
Make players explicitly accept EULA

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#340]
### Situation

When subscribing to Steam, the end user agrees to the Steam Rules:

https://help.steampowered.com/en/faqs/view/6862-8119-C23E-EA7B
https://store.steampowered.com/online_conduct/

While the Steam Rules are very clear, some players state those rules do not apply to in-game matches.

### Proposal

Add a page to the game, where the user explicitly agrees to above rules in multiplayer games. The page should be shown only the first time the player joins a game. The moment he agrees it should not show again. We might consider showing it once per new (stable) release to remind players Steam Rules apply.

**Comment by BenLubar** [comment]
It would make more sense to add the EULA via Steam - https://partner.steamgames.com/eula/563560/eulaedit/563560_eula_0

**Comment by BenLubar** [comment]
Created an EULA; going to wait until the 20th to publish it as part of the game metadata so the translators have a chance to get it first.

https://store.steampowered.com/eula/563560_eula_0
