### ISSUE TITLE
[FR] Give the option to change campaign in the lobby

### ISSUE THREAD

**Issue by FurtadoPires** [ReactiveDrop/reactivedrop_public_src#36]
The game need a way to change the current campaign to another in the lobby menu.

The current problem is that public dedicated servers are usually stuck in Jackob's Rest unless the owner change it to another, so it happens that a group finishes the campaign and leave because the players don't want to play the same campaign every time.

The change could be by a vote system or the current leader of lobby selecting which campaign he wants based on the available campaign in the server. It would also be good if we could vote another campaign in the middle of the game if the players want it.

Now if for some reason this option is already available in the game, then it should be more evident because I personally couldn't find it myself, and of course not considering console commands since it isn't available for those who aren't the host.

**Comment by BenLubar** [comment]
There's a 👍 icon at the bottom, or you can access it from the pause menu:
![image](https://user-images.githubusercontent.com/4257305/171759148-04ce497b-fa00-413b-be2c-29634f902483.png)

From there, click the "Change Mission" button at the bottom:
![image](https://user-images.githubusercontent.com/4257305/171759178-082241c1-099f-4bb6-b439-f38dc8bb1a55.png)

This will call a vote to change the mission.
