### ISSUE TITLE
Sound manifests are missing which results in sound lag 

### ISSUE THREAD

**Issue by geotavros** [ReactiveDrop/reactivedrop_public_src#363]
Looks like we lost map sound manifest files that should be located here:
Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop\maps\soundcache

This results in 0.5 seconds sound lag. For example when shooting from a weapon for the first time after map loaded.
Tested on HDD. 

Sound manifests need to be added to fix this issue.

**Comment by BenLubar** [comment]
https://developer.valvesoftware.com/wiki/Soundcache

Weird, does `snd_async_spew_blocking 1` print anything when this happens?

The article seems to say that the manifest files are only used to create `_sharedprecache.cache` and `<mapname>.cache`, which we've never shipped with, and that `maplist.txt` needs to contain all of the game's map names, which we haven't done.

**Comment by BenLubar** [comment]
> Yeah, I can repro the crash but I would have to figure out how to build the exact version of both the game engine .dll and steam_api.lib for the API that you are running against from our perforce databases.
>
> Can you just use +map mapname function and not -usereslistfile filename and run for each map separately and see if you can build up reslists that way ( I think you could build a .bat file that ran the reactivedrop.exe with each command line you needed ? )
>
> It is strange that it's crashing in steam, I suspect something in engine.dll is clearing out the steam_api after each level load in some unexpected way for this code path, unsure if it's a bad single callback function that's gone or if the entire callback stack is gone.
>
> [omitted reason as it contains information Yahn might not want made public] so can't do much more on this today, lmk if you are able to make progress by running the engine for each single map file instead.
>
> Or run a .bat file that runs with -usereslistfile maplist.txt and -startmap dm_* etc. over and over (each command starting with a new first map) until you get to the final map in which case the finalization step should occur successfully
>
> And once you have all the per map .lst files you have to run snd_rebuildaudiocache

**Comment by BenLubar** [comment]
Successfully built reslists, but none of the soundcache files listed on the wiki showed up and the master cache was about the same size as the one we currently ship. Found some nodegraph files that were outdated, so those are fixed, but as the game doesn't seem to even try to read the manifest files, the lag is likely from something else.

**Comment by geotavros** [comment]
Thanks. Couldn't reproduce this on the same PC after a few days. Possibly the lag was indeed from something else. Closing this as "cannot reproduce" for now.
