### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#37]
[From yuno on the forums:](https://steamcommunity.com/app/563560/discussions/2/3426689579755851655/)
> Would it be possible to change the layout of the weapon select menu to include more weapons at a time?
> I made a professional mockup of what I imagine it to look like:
> ![a grid of weapons](https://user-images.githubusercontent.com/4257305/171984212-e424c7b1-ff6f-470e-a97c-b584ea251c65.png)
>
> The layout change of the mission select screen was one of the best changes to come to ASRD so maybe you could do the same for the weapon menu?

---

Tabs for inventory view:
- [x] Weapons
- [x] Medals
- [x] Swarmopedia replacement

Weapons:
- [x] Replace briefing weapon selection
- [x] Ensure all stats are correct
    - [x] asw_weapon_rifle
    - [x] asw_weapon_prifle
    - [x] asw_weapon_autogun
    - [x] asw_weapon_vindicator
    - [x] asw_weapon_pistol
    - [x] asw_weapon_sentry
    - [x] asw_weapon_heal_grenade
    - [x] asw_weapon_medical_satchel
    - [x] asw_weapon_ammo_satchel
    - [x] asw_weapon_ammo_bag
    - [x] asw_weapon_shotgun
    - [x] asw_weapon_tesla_gun
    - [x] asw_weapon_railgun
    - [x] asw_weapon_heal_gun
    - [x] asw_weapon_pdw
    - [x] asw_weapon_flamer
    - [x] asw_weapon_sentry_freeze
    - [x] asw_weapon_minigun
    - [x] asw_weapon_sniper_rifle
    - [x] asw_weapon_sentry_flamer
    - [x] asw_weapon_chainsaw
    - [x] asw_weapon_sentry_cannon
    - [x] asw_weapon_grenade_launcher
    - [x] asw_weapon_deagle
    - [x] asw_weapon_devastator
    - [x] asw_weapon_combat_rifle
    - [x] asw_weapon_healamp_gun
    - [x] asw_weapon_heavy_rifle
    - [x] asw_weapon_medrifle
    - [x] asw_weapon_fire_extinguisher
    - [x] asw_weapon_mining_laser
    - [x] asw_weapon_50calmg
    - [x] asw_weapon_flechette
    - [x] asw_weapon_ricochet
    - [x] asw_weapon_medkit
    - [x] asw_weapon_welder
    - [x] asw_weapon_flares
    - [x] asw_weapon_laser_mines
    - [x] asw_weapon_normal_armor
    - [x] asw_weapon_buff_grenade
    - [x] asw_weapon_hornet_barrage
    - [x] asw_weapon_freeze_grenades
    - [x] asw_weapon_stim
    - [x] asw_weapon_tesla_trap
    - [x] asw_weapon_electrified_armor
    - [x] asw_weapon_mines
    - [x] asw_weapon_flashlight
    - [x] asw_weapon_fist
    - [x] asw_weapon_grenades
    - [x] asw_weapon_night_vision
    - [x] asw_weapon_smart_bomb
    - [x] asw_weapon_gas_grenades
    - [x] asw_weapon_t75
    - [x] asw_weapon_blink
    - [x] asw_weapon_jump_jet
    - [x] asw_weapon_bait
- [x] Weapon fact icons (the person who originally took this task decided not to, so I'm doing them myself)
    - [x] accurate_crouch
    - [x] aim_assist
    - [x] ammo
    - [x] area_radius
    - [x] bait
    - [x] blast_radius
    - [x] buff_radius
    - [x] bullet_spread
    - [x] damage
    - [x] deployable
    - [x] door_defense
    - [x] duration
    - [x] fire_rate
    - [x] generic_ammo_refill_clips
    - [x] generic_ammo_refill
    - [x] generic
    - [x] grenade_cluster
    - [x] healing
    - [x] heals_infestation
    - [x] heavy
    - [x] large_alien_damage
    - [x] level
    - [x] piercing
    - [x] projectile_speed
    - [x] range
    - [x] recharges
    - [x] reload
    - [x] rocket_aim
    - [x] secondary
    - [x] sentry
    - [x] shotgun_pellets
    - [x] specific_damage_bonus
    - [x] throwable
    - [x] unique
    - [x] warning

Medals:
- [x] Award HoIAF medals for season 1
- [x] Inverted Hat Trick medal
- [x] Automated HoIAF medal granting
- [x] Show in lobby
- [x] "Equip medal" button

Swarmopedia replacement:
- [x] Icons
- [x] Rewrite all descriptions as mechanical+lore a la Risk of Rain 2
    - Mechanics
        - [x] Drone
        - [x] Ranger
        - [x] Shieldbug
        - [x] Boomer
        - [x] Buzzer
        - [x] Parasite
        - [x] Mortarbug
        - [x] Harvester
        - [x] Xenomite
        - [x] Mender
        - [x] Biomass
        - [x] Grub
        - [x] Antlion Guard
    - Lore
        - [x] Drone (Prof. Julie Duval, IAF)
        - [x] Ranger (Bur Nable, Nanotrasen)
        - [x] Shieldbug (Prof. Julie Duval, IAF)
        - [x] Boomer (Dr. Brad Irwing, AMBER)
        - [x] Buzzer (Bur Nable, Nanotrasen)
        - [x] Parasite (Shaun Ming, SynTek)
        - [x] Mortarbug (Bur Nable, Nanotrasen)
        - [x] Harvester (Dr. Brad Irwing, AMBER)
        - [x] Xenomite (Dr. Brad Irwing, AMBER)
        - [x] Mender (Bur Nable, Nanotrasen)
        - [x] Biomass (Shaun Ming, SynTek)
        - [x] Grub (Shaun Ming, SynTek)
        - [x] Antlion Guard (Isaac Kleiner, Black Mesa)
- [x] Determine required kill counts

**Comment by Dumbstep** [comment]
Maybe he hasn't used the simplified weapon chooser, I think it's good enough.

**Comment by BenLubar** [comment]
Commandeering this issue for new inventory system.

**Comment by Nyubs** [comment]
i like the risk of rain 2 description idea.

**Comment by BenLubar** [comment]
Progress update:
![image](https://user-images.githubusercontent.com/4257305/189238090-143344c5-df3d-4709-ac7c-985f96592f15.png)
![image](https://user-images.githubusercontent.com/4257305/189238142-8ca4d493-da6c-4825-85ad-a65d7513f4a3.png)
![image](https://user-images.githubusercontent.com/4257305/189238185-fe398570-022a-4cec-89cf-b5087fb4eb75.png)

- [ ] I've commissioned an author for the Swarmopedia lore text. Can't share these yet, but the first draft of the drone article looks good.
- Some weapon models could benefit from changes:
    - [ ] Deagle has a weirdly large and very off-center hitbox.
    - [ ] MedAmp gun should look different than the default med gun, even if it's just a simple reskin.
    - [ ] Flashlight (and while we're at it, swarm grub) needs material changes to make it shiny like the rest of the weapons (and aliens). While we're at it (again) we might want to look into fixing the flashlight's center of gravity.
    - [ ] Reskin grenade box for gas grenades.
- [ ] Need to finish writing the weapon facts and then get some better icons made for the weapon fact types.
- [ ] The alien model viewer would benefit from a model of a chunk of floor floating in space to give the aliens a size reference.
- [ ] If there's a way to render particle effects or enable antialiasing on the model viewer, that could greatly improve the graphics.
- [ ] asw_weapon_50calmg is missing long name/description.
- [ ] Need to figure out a good UI for skill-scaling stats that works with mouse/keyboard/controller. In-game it'll just use whichever marine is selected, but out-of-game, it needs some UI.

**Comment by jhh8** [comment]
I like the drone article

**Comment by BenLubar** [comment]
The lore text for drones isn't in-game yet.

**Comment by BenLubar** [comment]
The final three Swarmopedia entries are being edited, and I hope to have them to the translators very soon.
