### ISSUE TITLE
Gas grenade box' skin broke

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#371]
After the October 20 update, the world item of gas grenades has lost their unique, distinguishable skin and became identical to freeze grenades.

**Comment by BenLubar** [comment]
![image](https://user-images.githubusercontent.com/4257305/197349117-6ec8f22f-7805-4ad4-b6d5-a3d79f427ff7.png)

Are you sure? They use the same model as frag grenades and freeze grenades, but a different skin.

**Comment by WhenTanksFly** [comment]
Wait what, it was intentional, really? In just two days I've bumped into too many players wondering why can't they pick up "freeze" grenades. If you need to zoom in this close to tell the difference between freeze grenades and new gas grenades, especially given normal camera distance that's not possible to change on will, it is a bad reskin, and it wasn't warranted in the first place.

**Comment by WhenTanksFly** [comment]
Months later the issue was somewhat addressed by the community https://steamcommunity.com/sharedfiles/filedetails/?id=2902211289

**Comment by BenLubar** [comment]
Fixed in beta for a while now, forgot to close issue (whoops).
