### ISSUE TITLE
Automatically temp-subscribe to addons the server needs to load the next map

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#377]
Need to investigate whether we can do this on an initial connect, but we can definitely load an addon from the workshop before a map change. Probably want a cvar-configurable timeout where the server will give up waiting on someone to be ready to load the map after some amount of time.

The addon would remain active until the session ends (that is, disconnect or exit), after which time it would be cached on disk by Steam for a while (in my experience, a couple of weeks) but not loaded by the game unless subscribed to or loaded again through this system.

**Comment by wawawawawawawa** [comment]
For maps, I'm pretty sure whenever I download it, I still have to restart rd client to actually join, otherwise there's some error.

For challenges, that would mean you could put models/sounds/particles, and be seen by all players regardless of subscription, that would be nice.

**Comment by BenLubar** [comment]
This is now partially implemented.

Set `rd_workshop_temp_subscribe 2` to automatically download and enable the addons for the lobby host's campaigns and missions and the addons for any challenges that have the `"required_on_client" "1"` set.

With the default of 1, it downloads the currently selected challenge addon if it has `required_on_client`, as well as any mission addon that is the "next up" map for bonus missions or deathmatch.

Setting the cvar to 0 makes it not download anything.

Still need to work on:

- [ ] Tell the lobby host our download progress and add UI for other players downloading things.
- [ ] Handle addon downloads when initially connecting to a lobby.
- [ ] Download required addons after voting to change map.
- [ ] Have a "force ready" state that kicks players without the required addons for the next map downloaded.
- [ ] Advanced setting for the new convar.

**Comment by WhenTanksFly** [comment]
> as well as any mission addon that is the "next up" map for bonus missions or deathmatch.
I don't think I understand that phrase. Aren't they solo missions and thus don't have anything "next up"?

And most importantly, file size. The campaigns Black Mesa and Reduction are about 1 GB each, and probably a few more are >0.5. Gotta account that some may take a while to download this, and some may not have the storage space required.

**Comment by BenLubar** [comment]
"next up" is a new feature that is currently in the beta branch where completing bonus missions picks a random next bonus mission and completing a deathmatch mission goes in a cycle to the next deathmatch mission in mission chooser order.

**Comment by BenLubar** [comment]
I don't think there's a way to *cancel* a workshop download request, so I might need to figure out if I can query the size of an addon before downloading it and request permission to download it from the player if it's over a certain amount.
