### ISSUE TITLE
Windows game bar / mode not recognizing the game

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#381]
The game bar overlay is not recognizing Alien Swarm: Reactive Drop in full screen mode. I am wondering, if the game bar doesn't recognize/support it, if perhaps game mode also won't work:

> When you use Game Mode, Windows prioritizes your gaming experience by turning things off in the background. When you’re running a game, Game Mode:
> - Prevents Windows Update from performing driver installations and sending restart notifications
> - Helps achieve a more stable frame rate depending on the specific game and system

~~The old Alien Swarm is detected properly. If I rename the `reactivedrop` folder and executable to `swarm`, the game is detected properly.~~ also not working in fullscreen.

To fix this, we would need to change something (in preferred order):

1) contact Microsoft and ask how to get the game detected properly;
~~2) 'just' rename `reactivedrop` to `swarm` in future releases.. not the preferred one, but it does the job..~~

**Comment by BenLubar** [comment]
I don't see anything in windows+G that says whether Alien Swarm: Reactive Drop is a game

**Comment by mithrand0** [comment]
It happens when in full screen. The overlay also suggests switching to windowed mode might resolve the issue.

**Comment by mithrand0** [comment]
![image](https://user-images.githubusercontent.com/28685162/199414706-76a0e4a8-5a40-4d54-b26a-6e457637db9c.png)

**Comment by mithrand0** [comment]
Seems it's not supported in L4D2 too, closing this issue.
