### ISSUE TITLE
White doors visually always fall the same direction

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#387]
Instead of landing on the opposite side from where attacked, the visible model of white doors with yellow stripes (which are commonly used in Nam Humanum and several Workshop campaigns, e.g., Edge) always falls in one certain side depending on how map author placed the door... while the invisible hitbox of the door somehow goes the proper way, like a normal gray door's would.
![doorus kindawrongusfallus](https://user-images.githubusercontent.com/112336094/200247629-ab2093b3-6f3e-4798-ab6a-1db0f9de3d4e.gif)

**Comment by BenLubar** [comment]
Code part of this is fixed, asked Beka to fix the model, and I'll write some documentation later today as well.
