### ISSUE TITLE
tilegen fails when rd_tilegen_instance resolves to a path not directly stored in the game's directory

### ISSUE THREAD

**Issue by daemonspring** [ReactiveDrop/reactivedrop_public_src#415]
## Problem

- There is an `rd_tilegen_instance` that resolves to `a.vmf` in a tile I'm using
- `a.vmf` is stored outside of the game files in a project folder as `<project>/source/content/tilegen/instance/ds-hulk/a.vmf`
- `<project>/source/content` is included as a search path within `gameinfo.txt`
- In tilegen I generated a layout and selected `File>Export VMF and Play Map`
- Compilation fails with the error `Could not open instance file ../tilegen/instance/ds-hulk/a.vmf`
- If I copy `a.vmf` into the game files as `reactivedrop/tilegen/instance/ds-hulk/a.vmf` then compilation succeeds
- There were many other normal instances used in the layout and they presented no problems

It seems that not all the search paths are followed during compilation for some reason. I didn't test it, but maybe this would affect vpked files too which would make it hard to distribute a tile set.

## Full Output

```
Building map from layout: maps\output.layout, emitting map file: output.vmf
Layout extents: Topleft: 0.000000 0.000000 - Lower right: 0.000000 0.000000
   Adjusted to: Topleft: -7 -51 - Lower right: 12 -29
Sending command bin/vbsp.exe -game ..\  output.vmf
  from directory Y:\software\Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop/maps
Valve Software - vbsp.exe (Jan 24 2017)
4 threads
materialPath: Y:\software\Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop\materials
Loading Y:\software\Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop\maps\output.vmf
Could not open instance file ../tilegen/instance/ds-hulk/a.vmf

Sending command bin/vvis.exe -game ..\ -radius_override 2500 output.layout
  from directory Y:\software\Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop/maps
Valve Software - vvis.exe (Jan 24 2017)
Vis Radius = 2500.00
4 threads
reading y:\software\steam\steamapps\common\alien swarm reactive drop\reactivedrop\maps\output.bsp
Error opening y:\software\steam\steamapps\common\alien swarm reactive drop\reactivedrop\maps\output.bsp
Sending command bin/vrad.exe -low -game ..\ -StaticPropLighting -nossprops -bounce 0 output.layout
  from directory Y:\software\Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop/maps
Valve Software - vrad.exe SSE (Jan 24 2017)

      Valve Radiosity Simulator     
4 threads
[Reading texlights from 'lights.rad']
[45 texlights parsed from 'lights.rad']

Loading y:\software\steam\steamapps\common\alien swarm reactive drop\reactivedrop\maps\output.bsp
Error opening y:\software\steam\steamapps\common\alien swarm reactive drop\reactivedrop\maps\output.bsp
Map Build finished!
CModelLoader::Map_IsValid:  No such map 'maps/output.bsp'
map load failed: output not found or invalid
```

**Comment by BenLubar** [comment]
I haven't looked at it for a while but if I remember right rd_tilegen_instance just turns into a func_instance after randomization, so it probably needs to be extracted like bik files are.

**Comment by daemonspring** [comment]
What's weird to me is that the compilation process has no issues at all finding regular `func_instance` pointing to paths external to the game folders but included in the search paths. It's only the instances chosen by `rd_tilegen_instance` that fail to work. The layout I used to test this had plenty of normal `func_instance`, even deeply nested, which were never mentioned in the output.

**Comment by BenLubar** [comment]
What's an example of a path that works in a raw func_instance? I wonder if rd_tilegen_instance is formatting it wrong

**Comment by daemonspring** [comment]
> What's an example of a path that works

`/ds/hulk/cap/E`, which is stored as `<project>\source\content\tilegen\instances\ds\hulk\cap\E.vmf`

**Comment by daemonspring** [comment]
Yes, that may work. The game has an `InstancePath` specified in `gameinfo.txt` (`tilegen/instances/`) which I presume is the default search location. Perhaps by deviating from this the tools fail to search mounted content and instead search only that one specific path in the game files.

It's also probably worth removing the part that adds the theme name to the path (i.e. the `ds-hulk` part), it confused me for a while and it will interfere with reusing instances between different themes.

**Comment by BenLubar** [comment]
Alright, will remove the theme name as well. Other changes are in the beta I pushed last night.

**Comment by daemonspring** [comment]
👍 Tested beta. Works without issues.
