### ISSUE TITLE
rd_tilegen_instance is not handled when nested inside other instances

### ISSUE THREAD

**Issue by daemonspring** [ReactiveDrop/reactivedrop_public_src#416]
Only when an `rd_tilegen_instance` is not nested within other instances does it get resolved by tilegen. Resolution of names and flattening of instances needs to be done recursively before compilation. There may be an arbitrary number of instances/randomly chosen instances within each other.

Nesting is immediately useful. For example, I have a base tile instance and then multiple rotated versions of this tile that are made available to tilegen. The rotations only include a `func_instance` pointing to the base tile which has been appropriately rotated. Much easier to maintain. Nested usage of `rd_tilegen_instance` is also essential for creating a very large amount of variation from only a few parts.

**Comment by daemonspring** [comment]
Note that nested `rd_tilegen_instance` can't be resolved without collapsing the containing instances. I vaguely recall seeing tools for collapsing vmfs before compilation to help deal with older versions of hammer, but I can't find those tools right now. There might be relevant existing code somewhere.

**Comment by BenLubar** [comment]
If we can collapse func_instance in tilegen's map modification code, we can do this.

**Comment by daemonspring** [comment]
Had a thought after waking up: If this process can be pulled out into a separate executable, it could just be run the same way vbsp/vvis etc are, just as the first step.

```
tilegen -> output.vmf -> [flatten] -> vbsp -> vvis -> vrad -> output.bsp
```

This would make the process available to hammer users so maps generated by tilegen can still be tweaked in hammer before being flattened. Best to preserve the most structured vmf at the top.

**Comment by BenLubar** [comment]
We could technically also make vbsp part of the tilegen process, so it would go tilegen -> vvis directly

**Comment by daemonspring** [comment]
It's best to keep things as composable as possible. A pipeline of smaller steps is much more flexible.

At some point I want to make a tool (probably in python) to compile all out of date maps in a project/package them into a vpk. Command line access to every step is ideal.

Also, I can see the value in having `rd_tilegen_instance` available to non-tilegen maps: Instead of manually arranging unimportant shelving for the billionth time, I can make some randomly generated shelf clutter. I'll probably be doing that anyway to populate tiles, best if it can be reused everywhere.

Actually, it would probably be useful if the seed used to power the random number generator behind the selection process could be set reliably; for the sake of consistent builds of the same vmf.

**Comment by BenLubar** [comment]
So, make tilegen part of vbsp? Seems reasonable.

**Comment by daemonspring** [comment]
No, I'm saying make the random instance resolving process a separate executable entirely. For convenience let's call this `rdrir.exe` (random instance resolver). It should read a normal vmf as input, and output a vmf with all the random instances resolved and the containing instances collapsed.

```
[example.vmf] -> rdrir.exe -> [example_resolved.vmf]
```

When tilegen exports a vmf, it shouldn't do anything special. It doesn't need to know anything about random instances. It should just output a regular vmf like it did before `rd_tilegen_instance` was introduced. Move all the special processes for handling random instances to `rdrir.exe`

When tilegen is told to export and play, currently it uses this pipeline to build the bsp:

```
tilegen -> [output.vmf] -> vbsp.exe -> vvis.exe -> vrad.exe -> [output.bsp]
```

Instead, this can be modified to:

```
tilegen -> [output.vmf] -> rdrir.exe -> vbsp.exe -> vvis.exe -> vrad.exe -> [output.bsp]
```

**Comment by BenLubar** [comment]
We don't have an external tool to do it (because we can't load workshop subscriptions without telling Steam that we're a game anyway) but instances are resolved recursively before writing the tilegen VMF now.
