### ISSUE TITLE
[question]Is .campaignsave mandatory?

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#429]
Deleting.campaignsave during a mission is OK. The game still runs as if nothing happens. And it is said that bonus missions don't have one. Not quite sure.

If the write permission of save folder is forbidden. The game can not create lobbies. On The other hand, if read is forbidden (while still can write), one can create lobbies. But will quite the lobby upon clicking start mission button.

Console showed the error of no filename provided or something.

**Comment by ywgATustcbbs** [comment]
For lobbies And servers having more than 8 players, it is better to give each player a chance to pick a marine after each restart instead of someone occupies a marine for a whole campaign. I searched convars and couldn't find one to achieve this. Then i turned to save file And failed with error message. Regarding its useage, the save file shouldn't be mandatory in gameplay.

**Comment by jhh8** [comment]
repicking your marine after every restart is very annoying, anyone i know agrees with that

**Comment by geotavros** [comment]
> Campaign saves are used by the game to remember which marines and weapons were selected, as well as some lobby statistics like number of retries.
Theoretically this could be stored in in-game memory, instead of writing to disk.
