### ISSUE TITLE
nodegraph state doesnt reset after instant restart

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#432]
node links seem to reset fine, however the connections that got locked because of aliens failing to navigate for some time do not get reset after instant restart

![image](https://user-images.githubusercontent.com/95616101/206911934-43809604-0153-458d-95b0-a54f6bd19953.png)

these links are green by default, got locked, map restarted, still red

**Comment by BenLubar** [comment]
Do they turn back to green if you destroy the rocks?

**Comment by jhh8** [comment]
not directly from breaking rocks, they turn back green if aliens try to navigate through them again and find out that they can

**Comment by jhh8** [comment]
fixed
