### ISSUE TITLE
Timor Station ending wires magnet marines

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#433]
Bottom-left from the landing pad is a small zone that actively teleports marines around, often preventing them from escaping; it's about where the wires lie. Finally saw this happen to someone else: [d_timorteleport_v7138.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/10220063/d_timorteleport_v7138.zip), low lerp settings might be related.

https://user-images.githubusercontent.com/112336094/207389539-c2e0efd2-7ac4-473a-a126-980ff1bb04d4.mp4

**Comment by BenLubar** [comment]
Hmm, that's close to, but not quite exactly where the displacements are sewn together.

**Comment by jhh8** [comment]
Should be fixed with todays update
