### ISSUE TITLE
Change to custom panel message for DNA sample in BioGen Corporation (rd-bio3biogenlabs)

### ISSUE THREAD

**Issue by Blueberryy** [ReactiveDrop/reactivedrop_public_src#437]
Should be changed to something like "Collect DNA" or something.
![reactivedrop_u7hLXdjxPv](https://user-images.githubusercontent.com/36592509/208401400-564f0f5d-21c1-475f-8fba-3c26d27bf995.png)

**Comment by BenLubar** [comment]
What other verbs might we want to replace "Use Panel" with? So far I can think of at least "Repair Circuit" for maps where the wire hack isn't a hack.
