### ISSUE TITLE
Burning drones attack faster than expected

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#445]
Imported from <https://steamcommunity.com/app/563560/discussions/2/6670425060425619954/>:

> **\-Fire drones:**
> (this one has been there since the beginning of the game).
> Ignite drones which is very but VERY problematic.
> When a flaming drone attacks, the fire ticks it suffers makes it attack 2 or even 3 times in less than a second which means that sometimes a single flaming drone can kill a vegas that is using this chainsaw against it because the tick of the 3 attacks combined is faster than the tick of the chainsaw which is necessary to kill a single drone.
> (before someone distorts my words, it is the fire drone that has a problem, not the chainsaw, please don't change chainsaw to solve the issue).

Will have to look into this. Sounds like the flinch animation is interrupting the attack animation but not the actual attack.

**Comment by GmaOrange** [comment]
I think this is nice personally. Different state of aggression of most common enemy. Additional threat requires more skilled gameplay. Quite realistic too that drones going mad under fire. Low amount of fire on maps too. So i am opposite against changing this.
