### ISSUE TITLE
asw_simple_hacking, something is wrong

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#452]
when that convar is set to 1, opening computer areas which are not locked stilll hacks them, and after the automatic hacking is done they close. on the workshop singleplayer challenge you have to reopen the turret computer area in nam3 twice or open pdas twice to read them

**Comment by BenLubar** [comment]
@jhh8 did today's beta fix it? if so it was downloading data (rather than hacking) that was happening when it wasn't supposed to

**Comment by jhh8** [comment]
seems good

**Comment by jhh8** [comment]
okay, there actually is a problem - computer areas can be locked and not have objectives tied to them like on bonus mission 1. shouldnt the check be for m_bIsLocked instead?

**Comment by BenLubar** [comment]
We probably need to split the logic for AI hacking versus AI downloading, then.
