### ISSUE TITLE
The compiled version cannot be used for games

### ISSUE THREAD

**Issue by qq578023708** [ReactiveDrop/reactivedrop_public_src#459]
I only replaced server.dll with the compiled version. When other players connect, they will receive a prompt: Server uses different class table, both the client and server versions are

Protocol version 7138

Exe version 7.1.3.8 (reactivedrop)

Exe build: 18:14:07 Aug 3 2020 (7940) (563560)

In addition to replacing the client.dll file, how can I resolve this version conflict

**Comment by BenLubar** [comment]
Either have the players change to the beta branch or use [the current released version](https://github.com/ReactiveDrop/reactivedrop_public_src/releases/tag/20221027) as a base for your changes.

**Comment by qq578023708** [comment]
Thank you very much. It works very well
