### ISSUE TITLE
Stuck on Yanaurus Mine elevator's collapsible platforms with another marine (& demo crash)

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#472]
Elevator felt lonely and just said no to exiting it. [d_why_to_fear_elevators.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/10465075/d_why_to_fear_elevators.zip) (v7.1.3.8), tick 18500+.

https://user-images.githubusercontent.com/112336094/213663814-b2caa8ff-3eaf-4301-8a86-5dc42bc19014.mp4

Also, jumping straight to tick 19000 causes the game to crash, minidump's inside the archive.

**Comment by BenLubar** [comment]
Should be fixed on the beta branch already, just need to do a backport.

**Comment by BenLubar** [comment]
Released hotfix.
