### ISSUE TITLE
[request] flammer boost fix only applies to ranked server

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#473]
I am a speed runner. I understand that the ranked servers are places for battle skill competition. Banning all kinds of bugs and skips on ranked servers are reasonable. But to us speed runners, We treat bugs and skips as another kind of skills that need to learn and practice So that we can get a perfect flammer boost or something.

flammer boost is an old bug/glitch. Why not leave it as a game feature for non-ranked servers and lobbies. Some flammer boost spots need up to5 players' coop to save time. We have practiced for months to get a perfect run using flammer boost technique. The fix ruins all of our team's efforts. Just because some players are using it in ranked servers. 

To be honest, speedrun.com needs to upload video proof, those skips. Players will know these skips eventually. Those speedrun skills are not intend for ranked servers. So devs could just tell everyone that bugs, skips and mods are forbidden in ranked servers and one will get banned If He uses these "techniques".

Please leave some spaces for speed runners.

**Comment by mithrand0** [comment]
There are discussions about flamer boost, and leaderboards on the Steam discussion forums:
- https://steamcommunity.com/app/563560/discussions/2/3761102779884982811/
- https://steamcommunity.com/app/563560/discussions/2/3361397532252356972/

**Comment by ywgATustcbbs** [comment]
> There are discussions about flamer boost, and leaderboards on the Steam discussion forums already:
> 
> * https://steamcommunity.com/app/563560/discussions/2/3761102779884982811/
> * https://steamcommunity.com/app/563560/discussions/2/3361397532252356972/

yeah, that's me. That's my steam Id. I tried to post long comments in that thread. But since I'm using my phone and new steam app sucks. Once pressed The bottom navi button by mistake, all my texts have gone. So i decided to use github to post this comment.
