### ISSUE TITLE
[proposal] use code obfuscation in part of the source code

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#476]
This is originally proposed for protecting leaderboard. The core idea is not protect the game, But protect the communication or records send to lb server. Especially the cheat flag or something else. The idea is based on the following  assumptiins:

1. Change the memory overlay or data structures could help defending the game.
2. The defense won't last long because cheater could read source code to find out the key code easily.
3.  Code obfuscation could greatly increase the time efforts in finding the right code. But this will block most cheaters out.
4. Periodically re-obfuscate the core code will block almost all malicious code modifications. 
5. For asrd, i don't think one will have the passion to do code analysis
6. If dll is protected, it is easier to deal with cheat engine. Periodically obfuscate dll will be enough for almost all asrd cheaters.

This could protect the game in some areas. The obfuscated code releases as open source, technically this won't violate valve requirement.

Only The core game functions Such as networking, dll verification m, etc. Needs obfuscating.  Re obfuscate The core code every half a year with version change or similar verification method. This will protect the game form many malicious modification by.

**Comment by BenLubar** [comment]
Security through obscurity is not security.

**Comment by ywgATustcbbs** [comment]
> Security through obscurity is not security.

It doesn't matter whether the method is secured or not. It ia making cheating doesn't worth the efforts taken that matters.

Obfuscating using software is easy. But relatively hard and a tedious work for most cheaters. For some big titles, aome cheaters can earn money by selling cheating software to other Players. This will never happen for asrd until it can bring players huge amount of benefits.

Considering This situation. Asrd release un-obfuscated code and builds every day using cicl software with random networking verision number, i don't think there will be Such a cheater boring doing manual modification. At least automation software would be used. Release everyday will gretly influence normal match. But what if every week with a few obfuscations? What if release seasonally with strong obfuscations? Is there anyone who really have the time, efforts, skills and most importantly, patience to read analysis and modify the source code every 3 months, without any rewards except for lb and similar things?

**Comment by ywgATustcbbs** [comment]
> Security through obscurity is not security.

At least you can post my idea to forum to ask if anyone feels that it worth doing the analysis work compared to the rewards

**Comment by ywgATustcbbs** [comment]
https://github.com/andrivet/ADVobfuscator

this obfuscator should block most of cheaters. Worth trying

**Comment by BenLubar** [comment]
reopening this so it can get responses from other people

**Comment by mithrand0** [comment]
We have anticheat:

https://reactivedrop.com/anticheat/

It is installed on some of the servers and lobbies. This software is obfuscated and hardened. For obvious security reasons, we cannot discuss this part of the code in public.
