### ISSUE TITLE
Speedrun challenge

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#477]
A small part of the community does want to utilize game out of bounds bugs to do speedruns. The statement is, by fixing bugs in the main game, they can't speedrun anymore. 

We can't not fix bugs, but to satisfy this group, we can introduce a speedrun challenge. In this challenge, we can keep fixed bugs like `flamer boost` and `marine rolls` enabled, while fixing such out of boundary issues for normal gameplay. Also, we can further finetune the conditions for a speedrun this way.

Such challenges are uploaded to the leaderboards, in a speedrun category, which should satisfy this group.

**Comment by BenLubar** [comment]
This should be a leaderboard-whitelisted workshop challenge, not shipped with the game by default.

**Comment by BenLubar** [comment]
We can't change the asw_marine_rolls convar and call it a day because some speedruns want rolls and some want jumps.

**Comment by jhh8** [comment]
would it be possible to create a new flag for convars which would make the server not send times to the steam leaderboard when the convar's value is changed from default?

**Comment by mithrand0** [comment]
The challenge: [speedrun.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/10579001/speedrun.zip)

I prefer that someone from the speedrun community uploads and maintains this addon, so they can adjust it to their needs when needed.
