### ISSUE TITLE
Speedrun.com integration

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#479]
Come up with some new possible solutions. Sorry to post them here because i use a phone to edit texts and steam app is unfriendly to long text editing.

I see the current possible solution is to use speedrun.com, But few ssrd players knows the website. It needs recognition and promotion from the devs before it is accepted by the Asrd players. Technically, it can replace or integrate with the game to encourage players to perform runs that can be verified, and discourage/expose those cheaters, further maintaining a good community environment.

There are several solutions to integrate speedrun.com into lb. Followings are sorted based on the works needed.

1st solution. No need to change game logic. But to retrive info from speedrun.com and display it in game.
1. Split the current in-game lb screen into two parts, display verified speedrun.com results as verified on top half, and display the current lb as un-verified on the bottom half.
2. Done. Thus will encourage players to submit records for verification.

2nd solution is based on the 1st one:
1. contact moderators on speedrun.com, increase/expand speedrun categories for each map and difficulties. Sure, the moderator will have a lot of works to do. But i think community will get it done.
2. Retrieve data from speedrun.com, display them.
3. Done.

3rd solution (based on previous one):
1. invite some moderators to join devs team as long-term community menbers. 
2. Review And revise the current speedrun rules to force using speedrun challenge as proposed 
3. Recruit more community moderators.
4. Done.

4th solution:
1. Do as speedrun.com, Add a speedrun submitting page to the official website. User fills in their steam I'd and other game info, post a YouTube link.
2. Find some community moderators to verify the submitted runs.
3. Display them in the game and on the official website.
4. This need much more web coding.

5th solution. Integrate with autorecoding.
1. Send each demo md5 and sha256 strings to website to protect records from demo editing.
2. Community moderators verify top records,  websit auto verify other records using demo file checks.
3. No video and demo verification is required, unless it breaks the top 20 and 
4. Top 100 records.
5. Players who have broken top records will have several days or weeks to prepare video and/demo using local demo files.
6. Once demo uploaded to the website, check md5 in the database.
7. Once passed, run auto verification. And if needed, perform community verification.
8. Only permanently keeping top 20 or 50  demos for further reporting.

These solutions don't need much website resources. Perhaps, devs can try to contact/regrouping community members. I think it worth trying.

**Comment by mithrand0** [comment]
Integration would mean, someone needs to code it, it can be a lot of work.

**Comment by ywgATustcbbs** [comment]
> Integration would mean, someone needs to code it, it can be a lot of work.

Perhaps, can start with the easiest one.

fetch html metadata from an url is relatively easy using Python. Grab the info needed daily and cache them on official website. This part should be easy. Game Ui might take some time.

I think i can write a c# demo to fetch data from speedrun.com

**Comment by ywgATustcbbs** [comment]
> Integration would mean, someone needs to code it, it can be a lot of work.

https://github.com/speedruncomorg/api

This is speedrun.com official api, this may save most of the data fetching work

**Comment by mithrand0** [comment]
I we wanted to implement such thing into the game, it would need to be written in c++, which complicated things (at least for me).

**Comment by ywgATustcbbs** [comment]
> I we wanted to implement such thing into the game, it would need to be written in c++, which complicates things (at least for me).

https://github.com/yhirose/cpp-httplib

I guess it's http get/post the problem? Or json parser?

The api  itself is easy, Just use the get method (the url is specified by the api doc) that provided by  any httpclient lib. A json file with lb info is received. Then parse it using any json parser and retrieve data from it.



https://github.com/nlohmann/json
There are many similar But more light eeighted jdon parser

**Comment by BenLubar** [comment]
We have jsmn and ISteamHTTP in the game, but there are significant privacy concerns to doing a third party HTTP request every time someone does something in a game.

**Comment by ywgATustcbbs** [comment]
> We have jsmn and ISteamHTTP in the game, but there are significant privacy concerns to doing a third party HTTP request every time someone does something in a game.

Perhaps official website could be used to fetch and cache data, all steam users can retrieve cached data from official website.

**Comment by ywgATustcbbs** [comment]
> We have jsmn and ISteamHTTP in the game, but there are significant privacy concerns to doing a third party HTTP request every time someone does something in a game.

Another walk around is to piblish the json or further processed data to the steam forum using a bot, Then retrive them using within steamhttp.

**Comment by ywgATustcbbs** [comment]
>...there are significant privacy concerns...

I'm not sure but it's the thief party libs that raises the concerns. Am i right?

**Comment by mithrand0** [comment]
Ben means stuff like https://gdpr.eu/what-is-gdpr/

**Comment by wawawawawawawa** [comment]
Would it be worthwhile to contact speedrun.com to see if they would even want some partnership?
Obviously no point for me to message them if you guys are strongly against it, hence my question here first, but IMO even just a small UI linking to speedrun.com home page would already be a good step to make players thrive for recordings.

**Comment by ywgATustcbbs** [comment]
> Ben means stuff like https://gdpr.eu/what-is-gdpr/.

I don't understand. Those data are posted by speedeun.com user and are in public domain. If one wants to post runs via api, he must register apeedrun.com account and specify his token in the api. By registering, he already agrees the terms of use.

**Comment by mithrand0** [comment]
> > Ben means stuff like https://gdpr.eu/what-is-gdpr/.
> 
> I don't understand. Those data are posted by speedeun.com user and are in public domain. If one wants to post runs via api, he must register apeedrun.com account and specify his token in the api. By registering, he already agrees the terms of use.

Noticed.

When making an api call from the game to speedrun.com (i.e. showing the leaderboards of speedrun in-game), we would disclose the ip of the user. Ip addresses are considered person data in the eu, falling under gdpr.

If you mean, speedruns are posted outside of the game, that is fine. But in that case we could close the ticket, since no integration would be needed between game and speedrun.com

**Comment by wawawawawawawa** [comment]
Yes and no, even with a full integration, small steps can be made, with a simple link from main menu towards speedrun home page.

Obviously full integration would be awesome, but since technical limitations, first need to to just give an easier access to the website, which will make said website "officially accepted".

With zero integration (aka, not even a small link), there is no officialization, nor a show that such an option is something rd team would like to have (and as I said, I feel diverting peer-review towards community would be the correct way to tackle this, as it shouldn't be done by devs).

But yes, I feel just having rd stance on it with a small integration would already go long ways.

PS : I won't mind asking speedrun.com if they would want to do something, and maybe they even have ideas/solutions as I assume they already did such partnerships, but I would like to first know if you guys even think it's a possible solution.

**Comment by ywgATustcbbs** [comment]
Got It. So there are some walk aroubds

1. Get the data using official website server and cache the data. Then game clients retrive data from official server.
2. Post the cached data on forum using a bot, game clients retrive data from forum.
3. Directly state It in the game teens of use
4. Make an Ui switch, store the term of use using steam cloud
5. Check the locations of the user and black This function for eu users, Instead, show a string to tell them they can see verified records on speedrun.com

**Comment by mithrand0** [comment]
From Speedrun.com:

> Some operations the API offers require a user-context to work. In this case, an API client needs to authenticate on behalf of a registered user.

> To prevent excessive crawling of the data we make available and to ensure a good overall performance, requests to the API are subject to rate limits.

**Comment by wawawawawawawa** [comment]
This seems like quite some time investment though, and that's not even knowing if speedrun.com even agrees to this.
1) need to know if rd team want a partnership
2) need to know if speedrun.com want a partnership
3) start small (just a link to officialize stuff)
4+) look for improvement on integration / solutions for technical difficulties

But no point looking at 4) if 1) and 2) are not known.
Pretty sure 3) shouldn't require much time investment, but no point without knowing if both party want a partnership

**Comment by mithrand0** [comment]
> 1. need to know if rd team want a partnership

I prefer leaving this choice to the other members of the rd team.

**Comment by ywgATustcbbs** [comment]
> From Speedrun.com:
> 
> > Some operations the API offers require a user-context to work. In this case, an API client needs to authenticate on behalf of a registered user.

This is intend for posting new records. An user token is required in that case
 
> 
> > To prevent excessive crawling of the data we make available and to ensure a good overall performance, requests to the API are subject to rate limits.
> 
> Single ip or bot they don't want

Retrive data daily or wewkly will be enough, Since moderators also Needs time to verify a run. If official website could cache data, daily caching will be ok

**Comment by mithrand0** [comment]
> "You may not use any scraper, crawler, spider, robot or other automated means of any kind to access or copy data."

As home user, you might take such terms lightly, but as organization, we have to be a bit more careful. Of course if speedrun would agree, and there is a legal data agreement, then it would become something else. Even after that, It is still some work to implement.

**Comment by ywgATustcbbs** [comment]
> 

Here is another solution. 

1. Store the records in a local file that shipped with every game updates/patches.
2. The records would be added into the translation repo
3. community will update the records file manually, at least i can do this updating work.
4. The rest is Ui design

**Comment by mithrand0** [comment]
> "You may not use any scraper, crawler, spider, robot or other automated means of any kind to access or copy data."

We are not allowed to copy the data local.

**Comment by ywgATustcbbs** [comment]
> > "You may not use any scraper, crawler, spider, robot or other automated means of any kind to access or copy data."
> 
> We are legally not allowed to copy the data local. We don't own it.

It says no copy using robots. It does not say i can't copy data Manually, It doesn't say i can't store data to a local file

**Comment by mithrand0** [comment]
> > > "You may not use any scraper, crawler, spider, robot or other automated means of any kind to access or copy data."
> > 
> > 
> > We are legally not allowed to copy the data local. We don't own it.
> 
> It says no copy using robots. It does not say i can't copy data Manually, It doesn't say i can't store data to a local file

https://gdpr.eu/data-privacy/

Above link explains in-depth, what is required and what not. Since a lot of countries implement something similar, it's (legally) not as easy as you suggest.

**Comment by ywgATustcbbs** [comment]
Even If speedrun.com don't allows it,. We can post our runs for verification on steam forum. Community members could work as moderators. once confirned, records can be Manually uploaded into github repo. Only Needs a file to store It. This is the most essy solution that i can come up with. No legal issues.

The current lb has so many problems, why not do something.

**Comment by mithrand0** [comment]
> The current lb has so many problems, why not do something.

We tried, the public discussion of that is on the Steam forums.

 If you want to make a steam forum post about speedruns and rules, I am happy to pin it on top of the discussion board.

**Comment by ywgATustcbbs** [comment]
> > The current lb has so many problems, why not do something.
> 
> We tried, the public discussion of that is on the Steam forums.
> 
> If you want to make a steam forum post about speedruns and rules, I am happy to pin it on top of the discussion board.

Actually, that post is talking about how we can find a way to show verified records in game to everyone, It doesn't matter where to post the records. 

The issue is, the "new" board is recognized by the official. The dev team tells the community where to post the records for verification and the community will follow the instructions. 

I can suggest a solution, But i can't announce It.

**Comment by ywgATustcbbs** [comment]
> It's also not the integration you asked for in the first place..

Integration is not the purpose. The purpose is try to find a solution to show verified records in game that can partial replacing The current lb.. I tried my best you find a dolusyion to show verified records directly in the game to discourage cheaters.

Ideally, a little verified mark on the current lb will be enough. Then the problem comes to how to verify the record. Sunce you suggested in the steam thread that speedrun.com is recommend, So i tried to find a solution to integrate It. 

As the devs concern, the integration of speedrun.com is technically possible but has legal issues. 

So let's go back to what i really want to talk. Lb problems.

As far as i know, community wants to
1. Get ride of cheaters on lb, Especially for top records
2. At least distinguish cheating from real recirds

devs want to
1. Improve community environment, get rid of or discourage/punish cheaters.
2. Do less coding works If posdible
3. No legal issues

Based on these, i think we have one possible solution.
1. All top records need a community verification. Those video links could be posted on forum for verification. All devs need to do on this is add a speedrun verification sub-forum Just as bug reports, post requirements.
2. User post their video proofs. Devs do nothing
3. Find some community moderators to do the work. If there is only a few moderators, only verify top records. devs do nothing.
4. Once verified, community moderators will collect record info periodically.
5. The devs has to find a way to put a verified mark according to community modrrators. The devs could assign some trusted community members to do manual marking.
6. Modify The current lb display method s bit. Show The verified mark.

**Comment by ywgATustcbbs** [comment]
> > "You may not use any scraper, crawler, spider, robot or other automated means of any kind to access or copy data."
> 
> We are legally not allowed to copy the data local. We don't own it.
> 
> Personally, I would love speedrun integration, it just has legal and some technical caveats to do so.

Oh God, you've made a big mistake on this.

In The sperdrun.com api page, It clrary states:

>Content License
>As with the [main website](https://www.speedrun.com/), all original content provided through the API is licensed under [CC-BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/). Images and videos are copyright of their respective owners.

**Comment by mithrand0** [comment]
> Oh God, you've made a big mistake on this.

I don't think I did, but I give up on the discussion after this line (:

I agree with @BenLubar this has privacy issues, tried to explain why. Maybe someone else can explain it better.

**Comment by ywgATustcbbs** [comment]
> Just give me a ping when you want a speedrun subcategory on the forums. If you prepare a text, that explains the rules, we can review it and make it sticky there.

Before we can put it into practice, i want to post a working workflow, please check if there any blokings.

1. Modify the game code a bit, print an identification string in the console Or chat with each upload call. The string can be the getrealtime() result, or something that can be used to identify the record(md5/sha256 is preferd). there are 3 updateleaderboardrecord calls in the source code, i don't knowwhich one to Modify. I think this is a piece of cake for devs
2. If The user wants that record to be verified, he must provide a video together with that identification string.
3. One verified, The identification string is collected by Community and subilmit to github repo. An verifiedrecords.cfg Or something elss is expected
4. Modify The leaderboard display function, show a veeified icon If the record is listed in the cfg file.

I think it is at least a working approach. It has many problems. But as a demonstration, It can work without much coding works. So i suggest to try it in beta as an experimental feature. Then we can improve the workflow.

**Comment by mithrand0** [comment]
I don't see how above can technically work when looking at the Steam SDK. Not without wiping existing leaderboards and a solution for everything mentioned here and on the Steam forums:

https://steamcommunity.com/app/563560/discussions/2/3361397532252356972/#c3761102779887394593

> It can work without much coding works.
> this is a piece of cake for devs
> The devs have to write

If you think it's such a piece of cake to write it, please go ahead! It's not that I don't want to implement something, but from my point of view, I just don't see above as easy and/or workable solution.

That said, I spent a lot of time repeating myself with basically the same message, which isn't that productive. Stepping out of this specific discussion and leave to to others for now :-)

**Comment by ywgATustcbbs** [comment]
> I don't see how above can technically work when looking at the Steam SDK. Not without wiping existing leaderboards and a solution for everything mentioned here and on the Steam forums:
> 
> https://steamcommunity.com/app/563560/discussions/2/3361397532252356972/#c3761102779887394593
> 
> > It can work without much coding works.
> > this is a piece of cake for devs
> > The devs have to write
> 
> If you think it's such a piece of cake to write it, please go ahead! It's not that I don't want to implement something, but from my point of view, I just don't see above as easy and/or workable solution.
> 
> That said, I spent a lot of time repeating myself with basically the same message, which isn't that productive. Stepping out of this specific discussion and leave to to others for now :-)

i wrote a working demo, the displaying of lb on other clients is similar to the last verification part. when verifiend, override the existing record using steamwork function. since i dont know how to show messages in chat window, and how to get the info needed, i only write some string to represent them. 

https://github.com/ywgATustcbbs/asrd_speedrun_lb_demo

**Comment by ywgATustcbbs** [comment]
> I don't see how above can technically work when looking at the Steam SDK. Not without wiping existing leaderboards and a solution for everything mentioned here and on the Steam forums:

currently the game use this functions to upload score

`SteamAPICall_t UploadLeaderboardScore( SteamLeaderboard_t hSteamLeaderboard, ELeaderboardUploadScoreMethod eLeaderboardUploadScoreMethod, int32 nScore, const int32 *pScoreDetails, int cScoreDetailsCount );`

in this function, the 2nd parameter `eLeaderboardUploadScoreMethod` can be used to force override an existing record.

**Comment by ywgATustcbbs** [comment]
@BenLubar 

Could you please kindly tell me These things, Or give me some hints. I am not familar with the source code and have no idea where to find them.
1.  the function name that display messages in chat
2. Function name that returns the current user steamid
3. there are two update leaderboard function calls in source code, which one is working or both of them
4. where is the part that display lb on loading screen
5. Where is the part that rename the demo file

I am working on integrate this demo into the source. The demo works fine but i don't know where to put it into the source code.

 The demo repo is posted in previous comment.

**Comment by mithrand0** [comment]
Your code cannot work, because:

![image](https://user-images.githubusercontent.com/28685162/215711854-36fb7f05-61db-4a81-8d7b-0026baa5b093.png)

> I don't see how above can technically work when looking at the Steam SDK. Not without wiping existing leaderboards and a solution for everything mentioned here and on the Steam forums:
> https://steamcommunity.com/app/563560/discussions/2/3361397532252356972/#c3761102779887394593

Need a solution for the trust issue first as described in the forums.

I prefer to not communicate any further here, it isn't productive for anyone. Happy to discuss this on Steam or Discord, maybe that way it's easier to explain why your suggestions will not work without solve other things first.

**Comment by mithrand0** [comment]
Regarding make them official, this is the poll we had a while ago:

![image](https://user-images.githubusercontent.com/28685162/215716963-5647bb50-d626-4f93-b345-358aea41f6e3.png)

**Comment by ywgATustcbbs** [comment]
> Happy to discuss this on Steam Chat or Discord, 

Both are OK.

**Comment by mithrand0** [comment]
Chat was more or less a repeat of what is already said above.

**Comment by mithrand0** [comment]
Talked about this, we won't integrate speedrun.com, or do time consuming modifications to the leaderboards for only a small group.

A forum post was created, as well as a page on the site:
- https://steamcommunity.com/app/563560/discussions/0/3758852249523668921/
- https://reactivedrop.com/speedruns-leaderboards/

The post will be posted into Chinese, when the translation is ready.

This means this issue is handled for now.
