### ISSUE TITLE
[bug] potential abusing of challenges

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#481]
This was originally intended to find a walk around for displaying info on search game menu. But i think there is a chance of abusing it.

The fact is, every player can upload a challenge. It does not need much learning. The challenge name is displayed on the found games screen. If i, for example, want to display some meaasges to others before they join, i can upload a do-nothing challenge named by that "message". Something like " skilled players only", "new players are welcomed", "speedrun", or even worse, spamming/rude titles. Moreover, this could use up the lb limit.

As far as i know, this won't violate any rule If all these "tchallenges" do not contain spam etc. Actually, i am planning to try it out.

**Comment by jhh8** [comment]
How are you expecting this to be solved, make it not possible to give names to challenges lol? Only challenges which are chosen by the devs will have leaderboards, if someone creates their own invalid leaderboard with a custom client then the leaderboard cleanup script will delete it

**Comment by WhenTanksFly** [comment]
Nicknames are potential of abuse as well, so what?

**Comment by mithrand0** [comment]
Until leaderboards are protected, nothing we can do.

For the discussion:
https://steamcommunity.com/app/563560/discussions/2/3361397532252356972/
