### ISSUE TITLE
new loading screens

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#483]
Tracking issue for the new loading screens I'm working on. They're rendered with Cycles (Blender's raytracing engine) at 4k, and they'll be shipped in DXT1 format at 2048x1024 with no mipmaps. Additionally, the loading screen code has been modified to always show loading screens at 16:9 aspect ratio, so there will be no stretching on 16:10, 4:3, 21:9, 48:9, (etc.) monitors.

Each of these textures is about a megabyte (to be more specific, they are exactly 1048736 byte files). Missions that are combinations of other missions will have loading screens that are combinations of those missions' loading screens. I did some math to generate a 256 pixel (at 1080p, 512 pixels at 4k) gradient for masking these types of images.

The process consists of decompiling maps using bspsrc (the importer doesn't like instances), running a preprocessing script I wrote to replace Alien Swarm specific entities with ones that the importer understands, importing the map into Blender using Plumber, adding a camera (usually near where the mission thumbnail was taken), manually tweaking lighting, fog, and materials, and then rendering. After the initial manual setup, renders take about 1-2 hours on my RTX 2060.

---

Jacob's Rest

- [x] Landing Bay
- [x] Cargo Elevator
- [x] Deima Surface Bridge 
- [x] Rydberg Reactor
- [x] SynTek Residential
- [x] Sewer Junction B5
- [x] Timor Station

Area 9800

- [x] Landing Zone
- [x] Power Plant's Cooling Pump
- [x] Power Plant's Generator
- [x] Wastelands

Operation Cleansweep

- [x] Storage Facility
- [x] Landing Bay 7
- [x] U.S.C. Medusa

Research 7

- [x] Transport Facility
- [x] Research 7
- [x] Illyn Forest
- [x] Jericho Mines

Tears for Tarnor

- [x] Insertion Point
- [x] Abandoned Maintenance Tunnels
- [x] Oasis Colony Spaceport

Tilarus-5

- [x] Midnight Port
- [x] Road to Dawn
- [x] Arctic Infiltration
- [x] Area 9800
- [x] Cold Catwalks
- [x] Yanaurus Mine
- [x] Forgotten Factory
- [x] Communication Center
- [x] SynTek Hospital

Lana's Escape

- [x] Lana's Bridge
- [x] Lana's Sewer
- [x] Lana's Maintenance
- [x] Lana's Vents
- [x] Lana's Complex

Paranoia

- [x] Unexpected Encounter
- [x] Hostile Places
- [x] Close Contact
- [x] High Tension
- [x] Crucial Point

Nam Humanum

- [x] Logistics Area
- [x] Platform XVII
- [x] Groundwork Labs

BioGen Corporation

- [x] Operation x5
- [x] Invisible Threat
- [x] BioGen Labs

Accident 32

- [x] Information Department
- [x] Powerhood
- [x] Research Center
- [x] Confined Facility
- [x] J5 Connector
- [x] Lab Ruins

Adanaxis

- [ ] Sector A9
- [ ] Nexus SubNode
- [ ] Neon Carnage
- [ ] Fuel Junction
- [ ] Dark Path
- [ ] Forbidden Outpost

Deathmatch

- [x] DM Desert
- [x] DM Deima (uses loading screen from Jacob's Rest)
- [x] DM Residential (uses loading screen from Jacob's Rest)
- [x] DM Test Lab

Bonus Missions

- [x] Space Port Catastrophe
- [x] Rapture
- [x] Bunker
- [x] IAF Marine Academy
- [ ] New Beginning
- [ ] Anomaly

Combos

- [x] Landing Bay + Cargo Elevator
- [x] Hostile Places + Close Contact
- [x] High Tension + Crucial Point
- [x] Power Plant
- [x] AMBER Complex

**Comment by ywgATustcbbs** [comment]
Do you need any help? I have rtx 2070s, think i can help rendering.

**Comment by BenLubar** [comment]
> Do you need any help? I have rtx 2070s, think i can help rendering.

Thanks for the offer, but I don't think I can take you up on it because my process involves a lot of stopping the render to tweak things over and over.

**Comment by BenLubar** [comment]
Alright, currently rendering Sewer Junction B5. Took a few attempts to get the water to not look like a flat surface.

As a result of the more complex scene, this one is going to take 2-3 hours instead of 1-2. (Currently about an hour into the final render.)

After that, I'll render Timor Station and hopefully get a beta build published before I go to sleep.

I've got the cameras placed and some modifications made for Deathmatch, Area 9800, Operation Cleansweep, and Tears for Tarnor. While those are rendering (and I'm inevitably stopping the render to fix tiny things), I'll have time to set up the cameras for the remaining campaigns and bonus missions. (Although Adanaxis will have to wait until the maps are ready to be added to the beta near the end of February.)

**Comment by DukeDukeEm** [comment]
Will this solve the problem with hard readability of the leaderboard on some backgrounds?
With, like a half-transparent dark background behind the text?

**Comment by BenLubar** [comment]
Hmm, I should probably make the loading screen leaderboard background more opaque.

**Comment by DukeDukeEm** [comment]
I didn't have time to look into the game when i wrote that comment. Now that I've seen it ... IMO it looks good already.
![image](https://user-images.githubusercontent.com/69652463/215562074-8a83608f-5185-4004-b9ef-bd23c61286b5.png)

**Comment by BenLubar** [comment]
Ah, I already did it and then forgot I had done it.

**Comment by BenLubar** [comment]
All currently-rendered loading screens are in the beta branch as of tonight. That is, Jacob's Rest, Area 9800, Paranoia, Operation Cleansweep, Tears for Tarnor, all deathmatch maps, and all currently-existing bonus missions except Bunker.

Bunker is currently rendering, and Accident 32's loading screens are queued to render after that. I'll check the results tomorrow morning. I've prepared the files for the remaining non-Adanaxis campaigns (Research 7, Tilarus-5, Lana's Escape, Nam Humanum, and BioGen Corporation) so that I can get straight to placing the cameras after.

**Comment by BenLubar** [comment]
Correction: Rapture and Train Station Catastrophe are not included in today's beta. They will be included in tomorrow's beta.

**Comment by BenLubar** [comment]
Alright, all of the official missions have loading screens. This issue is now on hold until Adanaxis is added later this month.
