### ISSUE TITLE
Steam inventory/Community medals - can't be showcased

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_public_src#485]
I can't save any of my Alien Swarm medals in a profile showcase, after adding them to the showcase mask and pressing the save button they do not show up.
Edit-mask:
![image](https://user-images.githubusercontent.com/69652463/215427741-06b67a89-faa2-4afb-ac8a-b43c475deb79.png)
Saved result:
![image](https://user-images.githubusercontent.com/69652463/215427919-aa222c03-ffce-4dfc-9a8e-4583d49309b8.png)

**Comment by BenLubar** [comment]
Going to forward this report to Valve; can't see any settings on my end that seem related to this.

**Comment by BenLubar** [comment]
Valve says this should be fixed now. A quick test on my profile supports that conclusion.

**Comment by DukeDukeEm** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/69652463/216555279-7a79a561-f461-43c1-890e-cf5cd290e78f.png)
