### ISSUE TITLE
[stats] Inconsistent use of the term speed runs and leaderboards

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#489]
On the stats website, the naming `leaderboards` and `speed runs` are both used in the same context. I prose to rename everything to strictly `leaderboards`, this also solves some misunderstanding in the purpose of these boards.

**Comment by BenLubar** [comment]
We're also going to (hopefully) have point-based leaderboards in the future (currently we have one, for Infinite Landing Bay), so speed runs is no longer the correct term either.

**Comment by BenLubar** [comment]
I've removed some of the headings. Let me know if I missed any.

Any ideas on what to change the `speedruns` in the URL to, or is that okay? It's there to differentiate between time and point-based leaderboards (for example, https://stats.reactivedrop.com/leaderboards/highscores/2809765323_rd-inf1-landingbay)

**Comment by mithrand0** [comment]
`speedrun` > `maptimes` ?

https://stats.reactivedrop.com/leaderboards/`maptimes`/0_asi-jac1-landingbay_01?lang=en

**Comment by BenLubar** [comment]
Went with `fastest`

https://stats.reactivedrop.com/leaderboards/fastest/0_asi-jac1-landingbay_01?lang=en
