### ISSUE TITLE
Control Steam profanity filter by server

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#490]
Steam has an option to filter language. These lists (regular expressions) are publicly available.

It would be nice, to give a server or client the option, to apply the same profanity filter as in the Steam discussions and chat.

**Comment by BenLubar** [comment]
Duplicate of #24

**Comment by mithrand0** [comment]
Thanks! Didn't see that one.

I wonder if it would be a nice to have to be able to set this on a server level. Not completely sure if it's a good idea, but it might solve some of the toxicity in some public lobbies. I let this one sink in for a while..

**Comment by BenLubar** [comment]
The settings for the profanity filter are in the Steam Store account page, and as far as I know there's no option for a game to override them.
