### ISSUE TITLE
Enhancement: sentry ammo and health bars

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#494]
Currently its only possible to see sentry's ammo when its placed and coming close to it or hearing the low ammo sound. Would be cool if there were bars for sentry's ammo and health when it is in your equipment slot (not placed yet), next to the sentry icon

**Comment by jhh8** [comment]
concept art
![image](https://user-images.githubusercontent.com/95616101/217524959-3abe6117-d4d9-4eb3-a7ee-ae0eb8a9486e.png)

**Comment by BenLubar** [comment]
I don't think health is stored when you pick up the sentry, so we'd just need an ammo bar

**Comment by jhh8** [comment]
you mean picking up sentry and placing it again makes it go back to 100% health?

**Comment by BenLubar** [comment]
I believe so, or at least I don't remember anything that sets sentry health on placement.

**Comment by jhh8** [comment]
better concept art
![image](https://user-images.githubusercontent.com/95616101/217589370-d21b3453-bb54-4d8e-a548-cd2ff8f58525.png)

**Comment by jhh8** [comment]
dmitriy suggests to put an ammo bar at the bottom near where the gun name is instead of at the icon

**Comment by BenLubar** [comment]
We can replace the ammo count for the case, since it's always going to say 001 there.
