### ISSUE TITLE
Tarnor - Oasis Colony Spaceport: Can't always hear incoming train announcer

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#498]
I've found the voice that announces the finish open to only be reliably noticeable when camping right next to the finish (which is hard due to rangers, buzzers and little space to deal with tripods), and often be nearly inaudible from about where the marines usually stay - near the stairs, especially relative to various fight sounds and a naturally loud bunch of sentries brought to the defense event from previous areas. Would be logical to be able to easily hear the thing arrive from the waiting hall. Not sure how much this relates to sound settings and marine/camera position/angle.

**Comment by geotavros** [comment]
Also at mission start there should be a voice line about train approaching, and players can see the train through windows. I remember it was bugging out randomly and not playing.
