### ISSUE TITLE
[proposal] two medal slots

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#499]
yes

**Comment by mithrand0** [comment]
![image](https://user-images.githubusercontent.com/28685162/218300783-cf1fba16-5902-4127-9a7b-ee15062a33ee.png)

**Comment by ywgATustcbbs** [comment]
Each promotion add one more medal slot.

**Comment by mithrand0** [comment]
> Each promotion add one more medal slot.

Personally, I wouldn't do that, it will become a mess in the interface.
