### ISSUE TITLE
UI - label size changes

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_public_src#501]
I Found a bug in the latest beta.

After entering an weapon- or equipment-detail-page in the collections you can read hovertexts/labels on some elements, these change size after leaving the screen (back to all-weapon-overview) and entering it again.

First call:
![image](https://user-images.githubusercontent.com/69652463/218226015-797f61bd-b2c7-49ee-93b5-0688226d6c94.png)

Second call:
![image](https://user-images.githubusercontent.com/69652463/218226023-da6930f1-b9fc-42de-9489-b96e9eb61c1c.png)

Apart from that bug, they should probably be replaced with the same rich tooltips drawn on the marine-selection-screen:
![image](https://user-images.githubusercontent.com/69652463/218226922-bcb94bbe-ec5c-48ab-a529-e61fb495ea2d.png)

**Comment by BenLubar** [comment]
Good catch.
