### ISSUE TITLE
zombine utilization

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#503]
a zombine is a zombie marine

my ideas:
have a netprop for asw_marine, m_bSpawnZombineOnDeath, which when set to true will spawn a zombified marine when he dies. also a vscript function to change the value of that
have a netprop for aliens, m_bSpawnZombineOnKill, which when set will spawn a zombine in the place of a marine that the alien kills, also a vscript function
have a convar for challenge makers, something like rd_marine_chance_to_spawn_zombine which would make marines have that chance to spawn a zombine when they die (probably only death from aliens in that case)

would plan to use that in accident32 campaign, spawning zombines when marines touch the muon gem or when they die from a "green" alien

**Comment by BenLubar** [comment]
the great zom-bee-n versus zom-bye-n debate of 2023

**Comment by jhh8** [comment]
I read it as zombyen

**Comment by BenLubar** [comment]
(I meant zombine as in zombie marine versus zombine as in zombie combine)

**Comment by jhh8** [comment]
Implemented
