### ISSUE TITLE
client cannot display the top-level menu

### ISSUE THREAD

**Issue by qq578023708** [ReactiveDrop/reactivedrop_public_src#510]
I used sourcemod plugins when I used it !Admin or other commands, such as sm_ vote,

sm_ Votekick, etc., the game will appear unable to respond to the mouse click operation. It seems that there is a transparent mask layer on the game window, blocking my mouse click operation. At the same time, the console will display a file missing warning: Missing Vgui material vgui/plugin/message_ waiting
It seems that other players' clients will also be affected by the same. Maybe it's not just my client file is missing.

I try to place other material files in the corresponding location under the game directory. The console does not display the file missing warning, but still cannot display the plugin menu. It does not work properly. I do not know whether the problem belongs to sourcemod or the problem of the game. Sorry, I raise this problem here. If my description is wrong and incomprehensible, please ignore and close this issue

**Comment by BenLubar** [comment]
Ok, this is partially blocked: we don't really have access to the part of the code that's causing mouse inputs to break entirely after seeing a menu (or at least I haven't been able to find it), but we can hopefully just create a whole new menu system in cooperation with sourcemod and skip the problematic code in the engine altogether.

**Comment by BenLubar** [comment]
Code is now in beta. Just needs a switch flipped on the sourcemod side after release (or before).
