### ISSUE TITLE
Expand more perspectives

### ISSUE THREAD

**Issue by qq578023708** [ReactiveDrop/reactivedrop_public_src#513]
From the first person script of the challenge, we can find that the control 0 console parameter controls the camera's angle of view. At present, there are only God's angle of view and the first-person angle of view. Is it possible to add more angle support, such as the third-person angle of view, and the 2D angle of view. If there is a 2D angle of view, with some maps, it may be possible to create a horizontal shooting game like Super Contra, MOD. Ha ha, this is also another way to play

```c
void CASWInput::UpdateASWControls()
{
	ASSERT_LOCAL_PLAYER_RESOLVABLE();

	C_ASW_Player *pPlayer = C_ASW_Player::GetLocalASWPlayer();
	if ( !pPlayer || pPlayer->GetASWControls() == ASWC_TOPDOWN )
	{
		CAM_ToThirdPerson();
	}
	else
	{
		CAM_ToFirstPerson();
	}
}

// asw - sets us up for moving the camera around in demos
void ASWDemoCamera_f()
{
	if (!engine->IsPlayingDemo())
		return;

	engine->ClientCmd("firstperson");
	engine->ClientCmd("asw_hl2_camera 1");
	engine->ClientCmd("asw_controls 0");
}
```

**Comment by BenLubar** [comment]
If you want to create something side-scrolling, you may be able to do it with asw_controls 1, a custom pitch, and the y shift set to 0.

**Comment by WhenTanksFly** [comment]
Possibly relevant: we already have challenges that change camera position: [Perspective](steam://openurl/https://steamcommunity.com/sharedfiles/filedetails/?id=1172370870), [All In One](steam://openurl/https://steamcommunity.com/sharedfiles/filedetails/?id=2113890916) (Challenge's main menu -> Marine -> Point of view).

**Comment by qq578023708** [comment]
OK, I think I need to take a good look at it
