### ISSUE TITLE
GiveWeapon script function memory leaks edicts

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#514]
Reporting that a fellow challenge maker's game crashed from failed edict allocation supposedly because of spamming giveweapon function, does it not destroy the current weapon in the slot that the new weapon is being given to?

**Comment by BenLubar** [comment]
No, it drops the weapon.

**Comment by jhh8** [comment]
looks like youre right, the function seems fine
