### ISSUE TITLE
Add the option to turn off friendly injury by default

### ISSUE THREAD

**Issue by qq578023708** [ReactiveDrop/reactivedrop_public_src#519]
Add the option to turn off teammate damage by default. The purpose of this function is only to enable new players to get started as soon as possible. I think it is a good choice to start with the easiest difficulty. Of course, these switches can be adjusted to. When the new player is familiar with it for a period of time and the system prompts him to upgrade the difficulty, he can turn on the friendly damage switch and give a reminder

**Comment by geotavros** [comment]
Friendly fire is one of the core game mechanics which make the game fun. In my opinion it shouldn't be disable-able in the base game. However third party challenges(mods) have an ability to disable it. There already exist challenges in workshop that disable FF.

**Comment by mithrand0** [comment]
duplicate and/or related to #330
