### ISSUE TITLE
dedicated server workshop updates not working

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#547]
The dedicated server can only download the workshop addons once, any updates after that give an error:

`[AppID 563560] Updating workshop item details failed with Access Denied`

The only way to fix this, is by removing the `workshop` folder.

Issue is fully reproducible, log of one run included here:
https://pastebin.com/PtEabRn2

No `workshop.cfg` on the server, since it is ranked. Server uses stock workshop settings.

**Comment by mithrand0** [comment]
Not sure if related, but noticed workshop download goes into an endless loop, when `rd_workshop_unconditional_download_item` is set to `1`. 

Below item is the last mentioned, it gives up after a while, changing to lobby. 
https://steamuserimages-a.akamaihd.net/ugc/2028347262933939023/2B5AFCE1395E1D024B422295617DCEC7CF118257/

After lobby, download restarts, and eventually changes to lobby again. Server has no `workshop.cfg`.

**Comment by BenLubar** [comment]
Can you make Steamworks tickets? I think this one requires Valve's input.

**Comment by mithrand0** [comment]
Yes, I can create a ticket. Just want to check out of few things before doing so.

**Comment by mithrand0** [comment]
Right now, it works again.
