### ISSUE TITLE
[issue]unstable cpu performance on high end cpus

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#559]
This is not actually a problem, But rather an issue of cpu frequency management of game and OS. The game is friendly to low performance pcs, that means, The game has relatively low cpu load. When it comes to high end cpus, The cpu will stay in very low idle state during briefing. However, When pressing start game button, the sudden cpu load will push the os and cpu to change the state. This causes great jaggering about 2s. The same issue happens on mission complete screen.

I found the issue because Currently i changed my cpu from 3900x to 7950x. Currently my solution is to manually change thread priority fom normal to high in taskmgr.

If possible, please add an option to increase cpu load on high end pcs to avoide the cpu state change. Or add an option to start the game on high priority to give a hint to the os on thread dispatching.

Btw,  #428 might have been caused by this reason

**Comment by BenLubar** [comment]
You can start Source Engine games with `-high` in the command line arguments to accomplish the second option.
