### ISSUE TITLE
S_StartSound and sm_admin missing sounds

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [ReactiveDrop/reactivedrop_public_src#563]
When try open sm_admin and use buttons i see in console message:

S_StartSound: Failed to load sound 'buttons\button14.wav', file probably missing from disk/repository

I guess there use more sounds not only button14.wav, need check.

**Comment by BenLubar** [comment]
The sounds were accidentally not included in the hotfix update, but they are prepared for inclusion in the April 20th release.
