### ISSUE TITLE
[bug]HUD missing one marine

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#566]
verision:  RC
note the last marine didn't show up on HUD.  Res.1920*1080

https://user-images.githubusercontent.com/11514506/231442416-b0d02aa6-ef94-4b1c-b863-231dcfb7e780.mp4

**Comment by BenLubar** [comment]
Weird, I thought we fixed this a long time ago.

**Comment by ywgATustcbbs** [comment]
Another issue found. At around 0:18 in the video.

![Screenshot_20230413_035012_com microsoft emmx](https://user-images.githubusercontent.com/11514506/231569459-42b1468d-9411-4d0d-a3f8-70c0278aee85.jpg)

**Comment by BenLubar** [comment]
I'm guessing they're either using asw_weapon_flechette or asw_weapon_ricochet, which don't have icons yet. They used to use the railgun icon.

**Comment by ywgATustcbbs** [comment]
Record 6, 12,... Jet pack
The video was taken hours before. Ignore this If you happened to clear the lb after the video.

**Comment by BenLubar** [comment]
Looks like there are a lot of modded entries on that leaderboard - https://stats.reactivedrop.com/leaderboards/fastest/0_rd-ocs1storagefacility

I'll make the system clean that up

**Comment by ywgATustcbbs** [comment]
If i remember, the in-game lb won't show and invalid entry. If they were marked as invalid right after the video, that is only a coincidence. But If they were marked as invalid before i recorded the video, that will be a glitch.

**Comment by ywgATustcbbs** [comment]
Double checked, the lb in both public and rc   version will show records ma4ked as invalid while it shouldn't.
