### ISSUE TITLE
Speedrun & Outstanding Execution achievements sometimes aren't awarded?

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#575]
Finished Invisible Threat in 1:15 deathless and didn't see the chat say anything about the speedrun achievement. Before the nerf the requirement was about 1:13, wonder if only achievement's description was updated (to 1:20) and not the actual time requirement to award it... If so, should check other recently changed achievements as well.
[d_visiblethreat_speedrun_v7139.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/11327441/d_visiblethreat_speedrun_v7139.zip) tick 17000 - 1:20 win, tick 29000 - 1:16 win

**Comment by WhenTanksFly** [comment]
Apparently this map/achievement itself is fine, and it's just another case of a more global problem with some achievements not always registering. To confirm whether this still happens (after seeing relevant entries somewhere in the changelog saying it's fixed) I'd have to find a few "wanna get achievements" groups... Might take a while... Wonder whether to close the issue until the problem is (hypothetically) met again. I have paranoidal trust issues with the changelog.

**Comment by BenLubar** [comment]
I don't remember when the change was made, but prior to the change, the notification that told the client to unlock a server-managed achievement was not marked as reliable, which meant that in times of high network activity (such as the end of a mission when all the stats are being sent and various entities are being disabled to avoid sounds carrying over through to debriefing) the packet could be dropped. Now that it's reliable, dropping the packet is only possible if the player is completely dropped from the server.
