### ISSUE TITLE
[bug] minigun shift aiming broken on dedicated servers

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#576]
shift aiming will have no influence on an autogun, which had in the past. The shift aiming a on minigun functions well.  

https://user-images.githubusercontent.com/11514506/234556367-da9079b4-7104-4cb2-95d5-949451bec7be.mp4

**Comment by geotavros** [comment]
Autogun wasn't ever affected by shift aiming.

**Comment by BenLubar** [comment]
Hmm, might be related to the check for velocity exactly equaling zero here

https://github.com/ReactiveDrop/reactivedrop_public_src/blob/6c44664378714f28b0abf7315a8fced8334c82cc/src/game/shared/swarm/asw_weapon_minigun.cpp#L459-L472
