### ISSUE TITLE
Grubs block movable objects like doors

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#580]
[d_grubs_hold_the_door.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/11357611/d_grubs_hold_the_door.zip) In a speedrun I had to nade over the door; in this demo just walking away from the door was enough to move the grubs.
Another case I remember (but unsure if it still happens) is them blocking the High Tension cart when it reaches the rock blockade and is about to explode. Any way grubs can be made squishable by such moving objects?

**Comment by WhenTanksFly** [comment]
Not Space Port Catastrophe's fault, just a case of the ongoing issue of aliens blocking movables.

[d_smol_but_stronk_v7141.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/11729865/d_smol_but_stronk_v7141.zip) An air grub blocked a door in DM Residental while rendering it indestructible. Realized the barricade at tick 9800, figured out why at tick 14200.

**Comment by WhenTanksFly** [comment]
![grub_strong](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/c13635e6-9f97-4fde-a6b1-fabd25f149d3)
~25 seconds after the block someone accidentally stepped on it, allowing the mission to progress.

**Comment by jhh8** [comment]
fixed in https://github.com/ReactiveDrop/reactivedrop_public_src/commit/13c9ddb0d1998ba9af752965a9ca19242abee989
