### ISSUE TITLE
[bug] NH3 right laser fence will not open after barrel has exploded

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#589]
To reprodece:
1. Double press e to open machine gun ui
2. Fire at barrel, not the red box on the wall
3. Press e to exit ui immediately.

See bug1.dem and bug2.dem, they are the same bug in two different game plays

https://1drv.ms/f/s!AjHhxntCwFpDfIqtC0SeMeaMScM

**Comment by geotavros** [comment]
AFAIK barrel is only for help there, you actually need to shoot the red box.
