### ISSUE TITLE
Sentry gun can be used to block spawn

### ISSUE THREAD

**Issue by FurtadoPires** [ReactiveDrop/reactivedrop_public_src#59]
I don't know if this is the intended behavior, but there's a glitch that you can use a sentry gun to totally block a spawn point of the swarms
![sentryblock](https://user-images.githubusercontent.com/7890832/172691563-3dc23e43-a3c8-4544-bff6-73aae31a3692.jpg)

In this example the sentry is being used to block the spawn of boomers

**Comment by BenLubar** [comment]
Spawn blocking is an intended mechanic.
