### ISSUE TITLE
Electric armor stats in-game show "Damage Blocked" twice

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#591]
I guess the first one should've been captioned "Used" or similar.
![Damage Blocked](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/c66805d6-c2f2-4af9-9af4-5a708bc971dc)

**Comment by WhenTanksFly** [comment]
While I'm at it, damage reduction is only mentioned in full text description but not right under item's name on this screen, at the left side with exact stats, or in classic mini stats display when hovering over chosen items in lobby, It at least deserves a spot at the left, with exact resistance %.

**Comment by BenLubar** [comment]
pushed to beta
