### ISSUE TITLE
Combat flares and incendiary mines collide with fire walls

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#595]
I don't recall any other equipment that'd collide with firemine fire, so doubt this is intentional.

**Comment by BenLubar** [comment]
There were actually a bunch but we fixed most of them.

**Comment by WhenTanksFly** [comment]
Other firemines (the thrown mine itself, before activating) too can collide with fire walls, though this doesn't seem consistent. Might need an exact distance for it to happen or something.

**Comment by BenLubar** [comment]
I'm making it so flares and mines are classified as grenades for the purpose of collision. I'm also making it so func_asw_fade will allow grenades (that is, pretty much all alien or weapon projectiles) through if the projectile spawned below it by default (but still solid if the projectile spawned above, so you can use a func_asw_fade brush to make a ceiling you can get on top of.

The one weapon I'm not sure about is laser mines. Would it make sense to be able to throw them at the ceiling? Or should they also ignore ceilings like other mines and grenades?

**Comment by WhenTanksFly** [comment]
> laser mines. Would it make sense to be able to throw them at the ceiling?

Where the mine attached is the explosion's origin, right? In a game where enemies walk on floor rather than crawl on roofs or walls like Spider-Man, roof mines would deal less damage than floor mines - and unlike wall-mounted ones, without any detection area benefits.

**Comment by WhenTanksFly** [comment]
Fixed in August 1 update https://steamcommunity.com/games/AlienSwarmReactiveDrop/announcements/detail/3690188204960315809
