### ISSUE TITLE
Text box may glitch inputs

### ISSUE THREAD

**Issue by FurtadoPires** [ReactiveDrop/reactivedrop_public_src#60]
Happened to me in lobby, after sent a message the text box stuck then didn't recognize inputs anymore. I had to leave the game through  task manager.
![20220608223440_1](https://user-images.githubusercontent.com/7890832/172745890-747a31ae-dd21-4ce7-8496-7335414b7427.jpg)

Didn't know exactly what was the cause thought

**Comment by Dumbstep** [comment]
Focus lost from chat box

**Comment by FurtadoPires** [comment]
Any way to workaround this if it happens again?

**Comment by FurtadoPires** [comment]
> > Any way to workaround this if it happens again?
> 
> I think ESC should be able

In my case it wasn't recognizing the ESC input either,  I had to finish the game process by using the task manager.

**Comment by Nyubs** [comment]
clicking in the chatfield somehow and pressing enter helps.
you have to to click right next to "say"

normally the other functions like esc menu consoles and go should still work. mapvote for example forces the chatbox to close.

**Comment by Blueberryy** [comment]
Is it fixed now?

**Comment by BenLubar** [comment]
should be fixed in yesterday's live build

if it's not, this can be reopened
