### ISSUE TITLE
Glitch spot on rd-nh03_groundworklabs  

### ISSUE THREAD

**Issue by FurtadoPires** [ReactiveDrop/reactivedrop_public_src#62]
In the end of rd-nh03_groundworklabs  during the final countdown, if someone jump in this specific spot they can glitch the countdown and make the ship to not land. People are using this to get "The Choice of Progress" achievement going there, glitching the counter then returning to lab room.
![glitch](https://user-images.githubusercontent.com/7890832/172747266-77696c04-69f4-4049-bc92-776d90f8cc79.jpg)

**Comment by BenLubar** [comment]
I believe a single marine reaching the escape area cancels the countdown, not sure.
