### ISSUE TITLE
[bug] new acc32 texture bug

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#636]
https://github.com/ReactiveDrop/reactivedrop_public_src/assets/11514506/69f79a23-0f98-4e65-8708-6c431ac1e299

**Comment by BenLubar** [comment]
@jhh8 is this one of the ones we hotfixed or is this different?

**Comment by jhh8** [comment]
Different, doesnt look like a mapping or texture bug. Textures are exact same as original but with env added

**Comment by WhenTanksFly** [comment]
Can confirm seeing similar issues today in some random game in Accident 32's 4th mission (e.g., most of finish elevator was black), don't remember whether self-hosted or dedicated. Cannot reproduce in singleplayer with or without mods.
Flashback to seeing Oasis Colony Spaceport miss a left wall in the medkit room before the green summoner; again couldn't reproduce in singleplayer without even restarting game (and with mainmenu cvar autorevert disabled months before).
I'd blame some server mods.

**Comment by jhh8** [comment]
Hm, the elevator was unchanged

**Comment by BenLubar** [comment]
found it; hotfix will go out as soon as I have the release build compiled

**Comment by BenLubar** [comment]
> Flashback to seeing Oasis Colony Spaceport miss a left wall in the medkit room before the green summoner; again couldn't reproduce in singleplayer without even restarting game

that one was a brush being too big and getting deleted by a spawner somewhere else in the map
