### ISSUE TITLE
Awful sound effects

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#639]
Traces back to [April](https://steamcommunity.com/games/AlienSwarmReactiveDrop/announcements/detail/3267945303133398274):
- New devastator firing sound. This nail screech is bad on its own and also doesn't represent weapon's power level. Was there anything not okay with the old one?
- Bullets amplified by leadership. What could possibly go wrong adding WW2 tank engine farts to rapid fire rifles.

Probably earlier:
- Multiple xenomites (and rangers?) dying at once, such as when sawing down a Harvester. Basically deafs the team for a second. Vaguely remember someone on Discord trying to fix this, apparently no success.
- Multiple tesla coils are pretty loud for their attack strength, and get extra bad if they all fire in one frame, which is common when using up Accident 32's many free tesla coils immediately after picking them up, or in challenges with offhand regen leading to similar mass-dumps.
- Restarting a mission occasionally bugs it all, playing the results theme only and no gameplay sounds 'til next restart. As I'm testing stuff typed above on vanilla config, this seems to happen a lot more often; may be related to me restarting missions via the pause menu before the red "MISSION FAILED" text goes away and the normal restart button becomes available. That and I usually have instant restart off due to memories of its catastrophic introduction.

I hid many issues behind addons for myself, but a friend trying the game out has reminded me how ragequit-inducing vanilla is, though pre-2023 problems (such as film grain and excessive screen shake from GL) are subject for some other day.

**Comment by BenLubar** [comment]
devastator, leadership, xenomite, and tesla coil sounds should be reduced in RC (will go out on Sep 1)

still need to figure out what race condition is causing the mission fail music to start playing *after* the mission fail screen is deleted
