### ISSUE TITLE
[bug] spawnner/pathing issues since recent update

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#644]
those screenshots are taken from videos before 8.16 update. 

para5 used to have two climbing spawners and acc5 used to have a side path. I am pretty sure that those spawnners/path existed until last update. I didn't see any changes about them in release notes or git commits (maybe i missed them).

![偏执症-5-新 mp4_20230821_222847 315](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/11514506/ec29921b-e662-4df1-95fd-0b13aab62e63)
![acc32-5-J5连接器 mp4_20230821_223334 768](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/11514506/a48035fe-0141-41e9-9b4f-334aa21e6aeb)

**Comment by jhh8** [comment]
very weird chain of debugging this para5 climb thing, compiled it myself and works fine - seems fix is just to recompile the map, maybe something broke while compiling

**Comment by ywgATustcbbs** [comment]
> very weird chain of debugging this para5 climb thing, compiled it myself and works fine - seems fix is just to recompile the map, maybe something broke while compiling.

if i remember correctly, the two spawners at the end of Jacob 4 also have the same issue at normal difficulty

The screenshot comes from an old version months ago

![24500316930489132](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/11514506/6598c645-6a07-457c-b3ee-e437d99139ee)

**Comment by BenLubar** [comment]
Paranoia bug is https://github.com/TeamSpen210/HammerAddons/issues/235 - can't use parallax-corrected cubemaps in par5 until it's fixed.

Accident 32 bug fixed as well for next week's patch, let us know if it happens anywhere else.

**Comment by ywgATustcbbs** [comment]
> Paranoia bug is [TeamSpen210/HammerAddons#235](https://github.com/TeamSpen210/HammerAddons/issues/235) - can't use parallax-corrected cubemaps in par5 until it's fixed.
> 
> Accident 32 bug fixed as well for next week's patch, let us know if it happens anywhere else.

Jacobi4 has a similar issue as mentioned above. the alien shooter spawner behind the window at the end area also failed.
