### ISSUE TITLE
[bug]fps_max is overrided unexpectedly

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#645]
Please turn audio on. The voice sounds bad and volume might be too high. But still audible i think.

https://youtu.be/xNyK8qZnQOk?si=XUH3trdThj-ayT-0

**Comment by BenLubar** [comment]
`rd_override_fps_max`

**Comment by ywgATustcbbs** [comment]
> `rd_override_fps_max`

Thank you. It works. But why fps_max is reset by changing missions. I can't find a newmapsettings.cfg file in cfg folder

**Comment by mithrand0** [comment]
`fps_max` was always reset for me between missions (probably some engine internal thingy, never cared to find out), that's why I created `rd_override_fps_max` back then.
