### ISSUE TITLE
[question] about font change in commit 31cb2b8

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#648]
In commit 31cb2b8. Font changes were reverted, But i think the comment says it is just a temporary revert.

 I don't know who has suggested using ZCOOLQingKeHuangYou font. But i don't think it's a good idea to use it in the future. That font is not a widely accepted font, at least for chinese. 

Some widely accepted fonts for formal printing in chinese are
1. Songti. (Has the same role as serif font family's Roman family, chinese version of times new roman. the most widely used formal printing font. But not a good font family for screen displaying)
2. Fangsong/simsun ( Also a serif font family that widely used by chinese government in its documents. Also not good for displays)
3. Heiti (has the same role as sans-serif fonts in English. NotoSansCJK falls into this font family)
4. Kaiti (has a similar role as italic. A hand writting style font family)
5. Lishu (an old-school style font family. Has a similar feeling of gothic.)
6. Youyuan (this font gives readers feelings of unformal, childish. As far as i know, this font is misty seen in children or teenage books. Sometimes it is used to replace Heiti, such as in movie subs)

Some big titles will choose or create fonts matching their s, But i don't think asrd should do this. Heiti works fine in this situation. If needed, you can create glyphs for mission end instead of using another font, There are only 16-20 glyphs in chinese.

**Comment by BenLubar** [comment]
Multiple people have given me exactly the same feedback, both before and after the temporary revert. I'll go ahead and delete the font from the repository.
