### ISSUE TITLE
[Bug] Invisible textures in some places at Oasis

### ISSUE THREAD

**Issue by Blueberryy** [ReactiveDrop/reactivedrop_public_src#653]
Vent has no textures
![reactivedrop_aNpLnKqOoQ](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/36592509/3a108c50-de66-4a22-9321-c082039f710b)
![reactivedrop_SjdEd3hPhT](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/36592509/1fe4fb84-b86d-470a-a711-910f124dcd11)
Idk what is this supposed to be but i guess door frame has no textures
![reactivedrop_BN8dxmYufM](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/36592509/15be6094-e887-4aa4-a3b4-7951ed22ba1c)

**Comment by WhenTanksFly** [comment]
Reminds me of #636:
> Flashback to seeing Oasis Colony Spaceport miss a left wall in the medkit room before the green summoner

> that one was a brush being too big and getting deleted by a spawner somewhere else in the map

Is the problem re-emerging?

**Comment by Blueberryy** [comment]
> Reminds me of #636:
> > Flashback to seeing Oasis Colony Spaceport miss a left wall in the medkit room before the green summoner
> 
> > that one was a brush being too big and getting deleted by a spawner somewhere else in the map
> 
> Is the problem re-emerging?

I'm using beta branch and it's there too.
Plus i can tell that not only me has this issue, i've watched some streamer and he has this problem too, can't prove a clip of stream though

**Comment by BenLubar** [comment]
weird, it's the same places that were breaking before. I wonder if something got accidentally reverted.
