### ISSUE TITLE
[Question] Friendly fire for nuclear payload

### ISSUE THREAD

**Issue by Blueberryy** [ReactiveDrop/reactivedrop_public_src#657]
Is it supposed to be disabled? You can damage that payload on new Reduction campaign and lose because of shooting it

**Comment by jhh8** [comment]
It's intentional, theres nothing much that damages it despite from FF so at least that makes the mission a little bit harder

**Comment by Blueberryy** [comment]
> It's intentional, theres nothing much that damages it despite from FF so at least that makes the mission a little bit harder

thanks for info

**Comment by jhh8** [comment]
Also, you can now heal the bomb 4 times by hacking it instead of only once like in original
