### ISSUE TITLE
Vscript function "ClientPrint" could not correctly convert a untranslated string prefixed by TextColor in the chat.

### ISSUE THREAD

**Issue by IAFCrash** [ReactiveDrop/reactivedrop_public_src#680]
Execute this Vscript code below:
`ClientPrint( null, HUD_PRINTTALK, TextColor( 0,0,255 ) + "#rd_challenge_name_asbi" );`

We can get the correct translated string in the **console**:
![image](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/46397575/ca7e537f-52bc-4482-b64b-a5879a4c2566)

Howerver, we get untranslated string in the **chat**:
![image](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/46397575/0d0a987e-8871-43be-8f1b-95795dea7074)

**Comment by BenLubar** [comment]
This is actually a bug in the console, not the ClientPrint function.

For a translation key to work, it needs to be the entire string. TextColor returns some control characters, so what you need to do here is put the translation key in a separate string and use a formatting parameter to combine it with the text color:

```
script ClientPrint( null, HUD_PRINTTALK, TextColor( 0, 0, 255 ) + "%s1", "#rd_challenge_name_asbi" );
```
