### ISSUE TITLE
Show only English CC

### ISSUE THREAD

**Issue by 906bc906** [ReactiveDrop/reactivedrop_public_src#70]
I set interface language and game language to Korean.
But The game displays English CC, instead of Korean CC. Even though there's a [translated CC](https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/resource/closecaption_koreana.txt).

![image](https://user-images.githubusercontent.com/57206558/173040009-ce0fc522-e887-4d45-8941-0568fb02d120.png)

It seems to occur only in the lines of the commander.

![image](https://user-images.githubusercontent.com/57206558/173043141-087a70f7-b224-4d26-8bcc-6f0a2d3c3b84.png)

I tested this in S-Chinese (It also has [translated CC](https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/resource/closecaption_schinese.txt)), and same problem occured too.

**Comment by Dumbstep** [comment]
closecaption are not compiled into dat file

**Comment by Dumbstep** [comment]
https://help.steampowered.com/fi/faqs/view/73F2-8EEA-1113-69B2

**Comment by Dumbstep** [comment]
you can compile it and create a PR

**Comment by 906bc906** [comment]
> you can compile it and create a PR

Thank you for your advice. I compiled closecaption and confirmed it works well.
I made a PR #71 and please tell me If there's any problem in my PR, because I'm beginner in github.

**Comment by BenLubar** [comment]
Adding captioncompiler.exe to the build script so that this won't need to be updated manually anymore.
