### ISSUE TITLE
Remove "out of meds" phrase from radial menu's central option?

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#701]
Other marines' pools for the middle button are gameplay-meaningless chitchat, yet both medics have a chance to lie about their ammo reserves. Pretty sure those lines shouldn't be there.
... Does the same issue apply to idle chatter?

**Comment by BenLubar** [comment]
Looks like there are 25 possible voice lines for each marine for that option. Currently working on annotating them in the source code. Right now they're just numbers with no explanations.

**Comment by BenLubar** [comment]
@WhenTanksFly alright, there's already quite a bit of overlap. what do we replace the two bad medic lines with? 

https://github.com/ReactiveDrop/reactivedrop_public_src/blob/15fef4b9a2e5e4df623d50a13a089b68238d82a8/src/game/server/swarm/asw_marine_speech.cpp#L1001
https://github.com/ReactiveDrop/reactivedrop_public_src/blob/15fef4b9a2e5e4df623d50a13a089b68238d82a8/src/game/server/swarm/asw_marine_speech.cpp#L1046

**Comment by BenLubar** [comment]
Personally I'd go with incoherent screaming but I'm also open to actually good suggestions.
