### ISSUE TITLE
Fast reloading deflects the trajectory of bullets consistently

### ISSUE THREAD

**Issue by squillisky** [ReactiveDrop/reactivedrop_public_src#705]
Whit Precision Rail Rifle it is easier to see, but happen whit other weapons. Every time you fast reload and fire the bullet start to the left and then go to the right of the aim reticle. Probably because of the incomplete animation of the reload caused by the fast reload. It make harder to hit and align important shot. It make even harder to use the rail rifle that it is already hard. I suggest to cut the animation or correct the trajectory.
![20240107142650_1](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/155894585/d3cbae62-617f-48ad-adbc-b0a5e7adb7d4)
![20240107142703_1](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/155894585/dd1616bf-bc95-4406-a880-8c4b570e6b03)
![20240107142720_1](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/155894585/f21b8537-75bf-48a5-ae0a-11b9dc3f256a)
![20240107142741_1](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/155894585/cf09c973-914e-4ff3-9ca9-e875ece31cae)

My PC has:
Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
RAM 	16,0 GB
GPU         Radeon RX 590 Series
Windows 10 Pro version	22H2

Thanks :)

**Comment by BenLubar** [comment]
I think what we're going to do for this is snap the marine back to a neutral animation state if you fire while playing the reload animation.

**Comment by BenLubar** [comment]
It's not the gun moving during the reload animation causing the shot to be off the mark. Something else is going on.

https://github.com/ReactiveDrop/reactivedrop_public_src/assets/4257305/3612423b-e232-4806-9058-f93a72ecf153

**Comment by squillisky** [comment]
I'm curious. Why do you think that?

**Comment by BenLubar** [comment]
The white line in the video is where the bullet went on the server. The server doesn't play the reload animation, so the gun moving isn't what's causing the bullet to go way off course. It seems like the aiming is somehow shifting to the right shortly after a reload.
