### ISSUE TITLE
Several spawners and objects missing since last few updates

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#706]
**Jacob's Rest - Rydberg Reactor**: Rangers are supposed to (re)spawn from the 2 holes at the left side of the final defense area. Only the tripod spawner functions now. I wouldn't mind adding extra reinforcements there, I've always felt lonely waiting for the double vault door.

**Tilarus - Communication Center**: The biomass after 2 hidden ammo boxes, 4 hidden medkits, and the necessary door hack. Where did the biomass go? It was mostly decoration as it wasn't blocking the path, but still.

**Reduction - Silent Station**: At the final defense several vent entrances on the floor open on their own and then nothing crawls out of them. Would like to have extra targets to shoot at in this zzz zone.

**Reduction - Nuclear Escort**: At the first bombing choice (left or road) I haven't seen any mortars spawn in last 10-ish runs, is it only a chance or? In the Workshop version I've definitely seen the mortar emerge at the left air strike spot.

**Comment by jhh8** [comment]
rydberg rangers disappeared after ben tweaked alien hitboxes, bio in til8 was removed by orange to allegedly fix a crash caused by it

**Comment by BenLubar** [comment]
The weird thing is I'm pretty sure the ranger hitbox is *smaller* now than it used to be.

**Comment by WhenTanksFly** [comment]
Speedrunning Communication Center, just had the host crash twice where the first biomass used to be. Doesn't seem like biomass removal helped.
My demo is probably useless since I didn't crash, but there it is anyway: [d_comm-center_crash-near-former-bio-spot.zip](https://github.com/user-attachments/files/17007387/d_comm-center_crash-near-former-bio-spot.zip)

**Comment by WhenTanksFly** [comment]
Adding to the previous comment, I've witnessed at least 2 cases of a dedicated server dying near the same spot - this time around it was "[CN] [RANK] [GAMER] 60tick 3Mbps Server", a few minutes before this message. [d_comm-center_near-bio-crash.zip](https://github.com/user-attachments/files/17529851/d_comm-center_near-bio-crash.zip)
