### ISSUE TITLE
Tarnor - Oasis Colony Spaceport: Train arrival can push marines on stairs

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#717]
As the final defense ends and the escape ship alternative arrives, marines standing in some south spots get shifted about a roll distance to the left. 

https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/1d7fbb5b-16a1-4602-af22-848b32bdaf1a

The ticket includes a free levitating drone - I assume a fresh, just-spawned one is taken from behind the south door and shifted together with me, though for much longer distance.
I don't recall when the problem first manifested, but I think it wasn't there a year ago.

**Comment by BenLubar** [comment]
I think the drone got stuck to the train somehow and that's why you got pushed. If the train's collision was that wide, the train would push every squad that gets to that part of the mission.

**Comment by WhenTanksFly** [comment]
Probably should've attached the demo then. The one time I thought it's not necessary. [d_tarnor3_train_magic_t43500_v7144.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/14057810/d_tarnor3_train_magic_t43500_v7144.zip)
The train bringing an air drone is a common occurence though.
