### ISSUE TITLE
Area9800 - Landing Zone: Finish jettable before door opens

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#723]
It's possible to use jet boots to fly right into the finish zone through the vault door and solid ceiling, don't even need to do the final hack then.

https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/ceac52bd-15e5-49f7-add6-b58736569f14

**Comment by ywgATustcbbs** [comment]
isn't it a feature for speedrun?

**Comment by protofolius** [comment]
> isn't it a feature for speedrun?

It is indeed . can just about do it solo with this jump at the end . 
Without this there is no way as the door would take too long to open .

**Comment by WhenTanksFly** [comment]
There really needs to be an explanation on this one?
It makes no sense by thematic consistency: jet boots aren't supposed to phase marines through solid roof.
It shouldn't be possible from general game design perspective, as it's almost auto win - whoever flies into finish is now unreachable by enemies, on top of just having skipped half the map.
It's no good from teamplay point of view, as the rest of the team becomes dead weight and has nothing to do other than kill themselves. Sometimes _(a lot of the times - this got too widespread back before original post)_ as early as at the hackable indestructible door before the big hangar - 7 of 8 players don't get to play the game, likely to be eaten by hangar horde if they do open the door.

> isn't it a feature for speedrun?

It's irrelevant for speedrun achievements - you still have the rest of the team that has to get there using just their legs.
As for leaderboards-aimed, non-deathless runs - with this many cheaters may as well not bother. Besides, we shouldn't cater to solo rushers at the expense of normal public lobbies.

> Without this there is no way

No way for what? To survive there solo while team arrives? Don't you guys have sentries?
