### ISSUE TITLE
Reduction - Fallen City: Win denied by shieldbug blocking train door

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#731]
![darth plugus](https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/9ff4366a-f6fd-4883-87a5-a135ed458964)
[d_fallencity_shieldblock_t10500.zip](https://github.com/ReactiveDrop/reactivedrop_public_src/files/14400518/d_fallencity_shieldblock_t10500.zip) I tried to melee-push it, but it had nowhere to be knocked away due to all space around it already being taken by drones.
I suppose the mission completion trigger could be changed to not depend on door closure, and instead activate X seconds after all alive marines assembled at finish.

In retrospec, there might've been some way to hit drones via gl without killing self by aiming outside...

**Comment by BenLubar** [comment]
@jhh8 can we set the door to ignore things in its way? or hurt the shieldbug?

**Comment by jhh8** [comment]
Timer for mission completion sounds easier, you can also run out while its closing and softlock. Also would make speedruns more consistent

**Comment by jhh8** [comment]
Will have to write a script to see how long the door takes to close to get the timing right
