### ISSUE TITLE
Hitscan weapons have double trails, best visible when the weapon is held sideways

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#737]
Easiest reproducible by turning off laser sight, then crouching right before shooting:

https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/18001a7b-61c5-4a78-a394-756f647ee4ab

Vanilla:

https://github.com/ReactiveDrop/reactivedrop_public_src/assets/112336094/4ed5ae3f-b27f-4b5e-8d99-3b6903bd1d59

Somewhat reminiscent of #735 due to the sideways grip. Unable to extract any memories on when did the problem first manifest.

**Comment by BenLubar** [comment]
My guess is that one is the predicted tracer and the other is the server tracer (which shouldn't be visible to the person who did the prediction, but that narrows down the area of code I need to look at a lot)
