### ISSUE TITLE
Auto-reload doesn't initiate while secondary fire button is held

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#741]
Most common with minigun and ricochet rifle as those naturally utilize the secondary button held, but applies to all weapons except pump shotgun, tesla cannon and flamethrower.

**Comment by BenLubar** [comment]
I think we need a new flag that sits next to "secondary fire uses primary ammo" which is "secondary fire doesn't shoot"
