### ISSUE TITLE
Buzzer blur bugs out and turns into static screenshot

### ISSUE THREAD

**Issue by geotavros** [ReactiveDrop/reactivedrop_public_src#76]
When buzzer damages marines it should create a tiny blur effect that lasts less than a second. It actually looks nice when it works. 
However pretty often it bugs and instead of blur it just shows a static blured screenshot from some previous buzzer attack. 
Sometimes it just shows a very bright screenshot which flashes you. Other times it shows a black image. 

Example:
![20220611163337_1](https://user-images.githubusercontent.com/2202923/173203144-f6e9bff8-be7e-4322-878c-6d12e60258c9.jpg)
The screenshot was take on 4fun challenge where buzzers blur lasts ~20 seconds. So basically once player is hit by buzzer they see a static screenshot all this time and can't really play.

This is especially annoying on ASBI or maps where there's a lot of buzzers, like Paranoia campaign. 
It's not clear how to reliably reproduce this issue. 
On my current system it happens from 1-2 buzzer hits. On previous PC it was happening when Shieldbug, Boomer or Harvester were present and expensive reflective water. E.g. on Sewer Junction map. 

Workaround: disable Multicore Rendering in Video Settings. Restart game. Now the issue is gone completely. However with Multicore Rendering disabled the client framerate drops significantly on ASBI challenges. 

Note: It seems to affect mostly AMD CPU users. We have reports that on AMD CPUs it starts instantly while on Intel it happens rarely.

**Comment by Dumbstep** [comment]
But isn't that the author's intended setting?

**Comment by Dumbstep** [comment]
If players can disable blurring at will, this will make the challenge less difficult.

**Comment by BenLubar** [comment]
If we can get the blur working properly, we can remove the convar.

But right now, some people have working blur and some people have a blank screen or a framebuffer from several minutes ago.

**Comment by BenLubar** [comment]
https://steamcommunity.com/app/563560/discussions/2/3426690213930182375/

**Comment by BenLubar** [comment]
I have a report that it starts okay for the first hit and then gets stuck on an i7-7700k / gtx 1080

**Comment by geotavros** [comment]
More info on how to reliably reproduce the issue:
- In NVIDIA control panel set Max Frame Rate to 140. Apply.
- In game use these commands
map asi-jac1-landingbay_02
fps_max 0
Select marine and start mission
asw_motionblur 1
And walk forward. 

I'm not sure if it's related to FreeSync\G-Sync. All graphical settings are set to max, except blur and bloom are disabled. VSync ON.

**Comment by BenLubar** [comment]
so far there are 5 responses to the survey and they all have intel cpu/nvidia gpu, mostly borderless. most report having it work properly in the controlled test but that they have seen it get stuck in the past.

**Comment by BenLubar** [comment]
it might be related to when damage is dealt, as there's no buzzer (or any alien at all) where this one got stuck

https://steamuserimages-a.akamaihd.net/ugc/1831290544993348824/FCF86CA890CA17DF8D72D4CDB06769940DFD6979/
