### ISSUE TITLE
After picking up a X-33 Damage Amplifier, the damage-increase-effect still stays in where it was placed.

### ISSUE THREAD

**Issue by IAFCrash** [ReactiveDrop/reactivedrop_public_src#778]
After picking up a X-33 Damage Amplifier, its damage-increase-effect still stays where it was placed, instead of following who picked up it.

**Comment by BenLubar** [comment]
The particle effect is driven by the game code. It appears to work correctly (connecting to marines close to the amp and not connecting to marines far from the amp) in my testing, so this might be something else.

**Comment by IAFCrash** [comment]
What I mean is, it is the the function of damage-boost still staying where it was placed, instead of the particle effect.
For an example, a marine places a X-33 with a range of 200 units at ( 0, 0, 0 ), and then if the marine picking it up and walking to ( 400, 0, 0 ), he/she won't get the buff of damage-boost though the particle effect is on the marine.



> The particle effect is driven by the game code. It appears to work correctly (connecting to marines close to the amp and not connecting to marines far from the amp) in my testing, so this might be something else.

**Comment by BenLubar** [comment]
Alright, I fixed this but it's still not reliably connecting to the marine that's carrying it.

**Comment by WhenTanksFly** [comment]
...close this, since it's been fixed [1st of August](https://steamcommunity.com/games/AlienSwarmReactiveDrop/announcements/detail/4325228729898871022)?
