### ISSUE TITLE
Special medal for contributors

### ISSUE THREAD

**Issue by Dumbstep** [ReactiveDrop/reactivedrop_public_src#80]
How about it?

**Comment by jhh8** [comment]
nice, we had same thoughts. should be coming

**Comment by BenLubar** [comment]
I'd like different medals for different kinds of contributions - translation, programming, maps, challenges, art, etc.

**Comment by BenLubar** [comment]
names and descriptions are not final: https://github.com/ReactiveDrop/reactivedrop_translations/commit/6cb039d63aa54ba1f22f29fec37fc1e8a7fa9c40

**Comment by Dumbstep** [comment]
@BenLubar Some beta testers want to keep the error icon, they like this.

**Comment by jhh8** [comment]
i hate the missing texture icon

**Comment by Nyubs** [comment]
ben where is your and my bday medal for today?
