### ISSUE TITLE
Certain weapons have a noticeable delay between reaching 0 ammo and initiating auto-reload

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#801]
Mining Laser ~1.00s zomg why
Grenade Launcher ~0.40s
Burst/Shield Rifle ~0.30s
Tesla Cannon ~0.28s
Flechette Launcher (both) ~0.15s
Assault Rifle, Combat Rifle, Prototype Rifle, Autogun, Heavy Rifle ~0.08s-0.11s (getting low enough to not care?)
PDW, MedSMG, Minigun, Plasma Thrower ~0.06s
The category I expected to be affected the most - slower-firing sidearms like Vindicator or Marksman Rifle - works nearly perfectly.

One may argue there is skill in starting reload earlier than auto-reload would come, and I would reply: "bots exist". Then again, doubt GL needs a buff...

**Comment by WhenTanksFly** [comment]
Now Mining Laser primary fire broke: smol not-winded-up beam shows up momentarily, and is immediately cancelled. Altfire has the weapon function properly.

**Comment by BenLubar** [comment]
Good catch, whoops!
