### ISSUE TITLE
Incendiary Sentry uses 2 ammo per shot unexpectedly, effectively lying in stats

### ISSUE THREAD

**Issue by WhenTanksFly** [ReactiveDrop/reactivedrop_public_src#807]
The opposite situation of old flamer and old minigun, which were at some point normalised into 1 ammo per shot. Let's do the same to the flame sentry: halve its ammo consumption and magazine size.

**Comment by BenLubar** [comment]
Honestly I'd be fine with halving its ammo consumption if that's what's going on and leaving it at that - people don't seem to be using it very much due to it being basically just a worse incendiary mine.

**Comment by WhenTanksFly** [comment]
It does pretty well in its role, just that yeah the role is rarely desired due to firemines and turretplug existing. Still, it *can* kill off a horde on its own, already making it a lot stronger than the lv1 bullet sentry.
I suppose if bullet sentry gonna get buffed, so can the flame sentry, to keep up. Though at that point the upcoming railgun sentry will be hard to sell, and the explosive one will further fall off.

**Comment by BenLubar** [comment]
Turns out it's actually using 2.5 ammo per shot. Ouch.
