### ISSUE TITLE
advance settings arrow bug

### ISSUE THREAD

**Issue by Nyubs** [ReactiveDrop/reactivedrop_public_src#86]
clicking between first option and arrow takes the highlight of the HUD SPEEDRUN blabla away and you either have to go left or up from arrow to get it work again.  whole arrow area on the right isnt working.

**Comment by Dumbstep** [comment]
> wanted to post screenshot to explain for reproduce but cause the menu doesnt use custom cursor its invisible

Take pictures with your phone

**Comment by BenLubar** [comment]
will be fixed in tomorrow's beta
