### ISSUE TITLE
gasnade throw particle change?

### ISSUE THREAD

**Issue by Nyubs** [ReactiveDrop/reactivedrop_public_src#99]
is there a reason it got changed?
me as an artist dont get the change, so any coder can tell?
alot of particle overhauls now have a random new particle in it.

kinda sad.

**Comment by BenLubar** [comment]
Gas grenades were changed to have a trail so they are more visible.

**Comment by Nyubs** [comment]
can we use particle parts of the actual nade. or do we have to remake all gasnades colouraddons now?
and i thought people didnt see the actual gas, and its not about the nade themself
